apiVersion: batch/v1
kind: Job
metadata:
  name: job-fail-db-init
  namespace: tilt-integration
  labels:
    app: job-fail-db-init
spec:
  template:
    metadata:
      labels:
        app: job-fail-db-init
    spec:
      restartPolicy: Never
      containers:
      - name: db-init
        image: db-init
