apiVersion: batch/v1
kind: Job
metadata:
  name: tilt-k8s-test
spec:
  backoffLimit: 0
  template:
    metadata:
      name: tilt-k8s-test
    spec:
      containers:
      - name: tilt-k8s-test
        image: gcr.io/windmill-test-containers/tilt-k8s-test
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: tilt-engine-test
spec:
  backoffLimit: 0
  template:
    metadata:
      name: tilt-engine-test
    spec:
      containers:
      - name: tilt-engine-test
        image: gcr.io/windmill-test-containers/tilt-engine-test
      restartPolicy: Never
