// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto/daemon.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	internal/proto/daemon.proto

It has these top-level messages:
	Service
	Cmd
	Mount
	Repo
	GitRepo
	Output
	CreateServiceReply
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Service struct {
	K8SYaml        string   `protobuf:"bytes,1,opt,name=k8s_yaml,json=k8sYaml" json:"k8s_yaml,omitempty"`
	DockerfileText string   `protobuf:"bytes,2,opt,name=dockerfile_text,json=dockerfileText" json:"dockerfile_text,omitempty"`
	Mounts         []*Mount `protobuf:"bytes,3,rep,name=mounts" json:"mounts,omitempty"`
	Steps          []*Cmd   `protobuf:"bytes,4,rep,name=steps" json:"steps,omitempty"`
	DockerfileTag  string   `protobuf:"bytes,5,opt,name=dockerfile_tag,json=dockerfileTag" json:"dockerfile_tag,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto1.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Service) GetK8SYaml() string {
	if m != nil {
		return m.K8SYaml
	}
	return ""
}

func (m *Service) GetDockerfileText() string {
	if m != nil {
		return m.DockerfileText
	}
	return ""
}

func (m *Service) GetMounts() []*Mount {
	if m != nil {
		return m.Mounts
	}
	return nil
}

func (m *Service) GetSteps() []*Cmd {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *Service) GetDockerfileTag() string {
	if m != nil {
		return m.DockerfileTag
	}
	return ""
}

type Cmd struct {
	Argv []string `protobuf:"bytes,1,rep,name=argv" json:"argv,omitempty"`
}

func (m *Cmd) Reset()                    { *m = Cmd{} }
func (m *Cmd) String() string            { return proto1.CompactTextString(m) }
func (*Cmd) ProtoMessage()               {}
func (*Cmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Cmd) GetArgv() []string {
	if m != nil {
		return m.Argv
	}
	return nil
}

type Mount struct {
	Repo          *Repo  `protobuf:"bytes,1,opt,name=repo" json:"repo,omitempty"`
	ContainerPath string `protobuf:"bytes,2,opt,name=container_path,json=containerPath" json:"container_path,omitempty"`
}

func (m *Mount) Reset()                    { *m = Mount{} }
func (m *Mount) String() string            { return proto1.CompactTextString(m) }
func (*Mount) ProtoMessage()               {}
func (*Mount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Mount) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

func (m *Mount) GetContainerPath() string {
	if m != nil {
		return m.ContainerPath
	}
	return ""
}

type Repo struct {
	// Types that are valid to be assigned to RepoType:
	//	*Repo_GitRepo
	RepoType isRepo_RepoType `protobuf_oneof:"repo_type"`
}

func (m *Repo) Reset()                    { *m = Repo{} }
func (m *Repo) String() string            { return proto1.CompactTextString(m) }
func (*Repo) ProtoMessage()               {}
func (*Repo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isRepo_RepoType interface{ isRepo_RepoType() }

type Repo_GitRepo struct {
	GitRepo *GitRepo `protobuf:"bytes,1,opt,name=git_repo,json=gitRepo,oneof"`
}

func (*Repo_GitRepo) isRepo_RepoType() {}

func (m *Repo) GetRepoType() isRepo_RepoType {
	if m != nil {
		return m.RepoType
	}
	return nil
}

func (m *Repo) GetGitRepo() *GitRepo {
	if x, ok := m.GetRepoType().(*Repo_GitRepo); ok {
		return x.GitRepo
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Repo) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _Repo_OneofMarshaler, _Repo_OneofUnmarshaler, _Repo_OneofSizer, []interface{}{
		(*Repo_GitRepo)(nil),
	}
}

func _Repo_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*Repo)
	// repo_type
	switch x := m.RepoType.(type) {
	case *Repo_GitRepo:
		b.EncodeVarint(1<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.GitRepo); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Repo.RepoType has unexpected type %T", x)
	}
	return nil
}

func _Repo_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*Repo)
	switch tag {
	case 1: // repo_type.git_repo
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(GitRepo)
		err := b.DecodeMessage(msg)
		m.RepoType = &Repo_GitRepo{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Repo_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*Repo)
	// repo_type
	switch x := m.RepoType.(type) {
	case *Repo_GitRepo:
		s := proto1.Size(x.GitRepo)
		n += proto1.SizeVarint(1<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GitRepo struct {
	LocalPath string `protobuf:"bytes,1,opt,name=local_path,json=localPath" json:"local_path,omitempty"`
}

func (m *GitRepo) Reset()                    { *m = GitRepo{} }
func (m *GitRepo) String() string            { return proto1.CompactTextString(m) }
func (*GitRepo) ProtoMessage()               {}
func (*GitRepo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GitRepo) GetLocalPath() string {
	if m != nil {
		return m.LocalPath
	}
	return ""
}

type Output struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
}

func (m *Output) Reset()                    { *m = Output{} }
func (m *Output) String() string            { return proto1.CompactTextString(m) }
func (*Output) ProtoMessage()               {}
func (*Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Output) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *Output) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

type CreateServiceReply struct {
	Output *Output `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *CreateServiceReply) Reset()                    { *m = CreateServiceReply{} }
func (m *CreateServiceReply) String() string            { return proto1.CompactTextString(m) }
func (*CreateServiceReply) ProtoMessage()               {}
func (*CreateServiceReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateServiceReply) GetOutput() *Output {
	if m != nil {
		return m.Output
	}
	return nil
}

func init() {
	proto1.RegisterType((*Service)(nil), "daemon.Service")
	proto1.RegisterType((*Cmd)(nil), "daemon.Cmd")
	proto1.RegisterType((*Mount)(nil), "daemon.Mount")
	proto1.RegisterType((*Repo)(nil), "daemon.Repo")
	proto1.RegisterType((*GitRepo)(nil), "daemon.GitRepo")
	proto1.RegisterType((*Output)(nil), "daemon.Output")
	proto1.RegisterType((*CreateServiceReply)(nil), "daemon.CreateServiceReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Daemon service

type DaemonClient interface {
	CreateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (Daemon_CreateServiceClient, error)
}

type daemonClient struct {
	cc *grpc.ClientConn
}

func NewDaemonClient(cc *grpc.ClientConn) DaemonClient {
	return &daemonClient{cc}
}

func (c *daemonClient) CreateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (Daemon_CreateServiceClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Daemon_serviceDesc.Streams[0], c.cc, "/daemon.Daemon/CreateService", opts...)
	if err != nil {
		return nil, err
	}
	x := &daemonCreateServiceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Daemon_CreateServiceClient interface {
	Recv() (*CreateServiceReply, error)
	grpc.ClientStream
}

type daemonCreateServiceClient struct {
	grpc.ClientStream
}

func (x *daemonCreateServiceClient) Recv() (*CreateServiceReply, error) {
	m := new(CreateServiceReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Daemon service

type DaemonServer interface {
	CreateService(*Service, Daemon_CreateServiceServer) error
}

func RegisterDaemonServer(s *grpc.Server, srv DaemonServer) {
	s.RegisterService(&_Daemon_serviceDesc, srv)
}

func _Daemon_CreateService_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Service)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServer).CreateService(m, &daemonCreateServiceServer{stream})
}

type Daemon_CreateServiceServer interface {
	Send(*CreateServiceReply) error
	grpc.ServerStream
}

type daemonCreateServiceServer struct {
	grpc.ServerStream
}

func (x *daemonCreateServiceServer) Send(m *CreateServiceReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Daemon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "daemon.Daemon",
	HandlerType: (*DaemonServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateService",
			Handler:       _Daemon_CreateService_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/proto/daemon.proto",
}

func init() { proto1.RegisterFile("internal/proto/daemon.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x41, 0x6f, 0xd3, 0x40,
	0x10, 0x85, 0x6b, 0x92, 0x38, 0xcd, 0xa4, 0x49, 0xa5, 0x3d, 0x20, 0xb7, 0x08, 0x29, 0x58, 0x2a,
	0xe4, 0x80, 0x62, 0x48, 0x2f, 0x91, 0xe0, 0x00, 0x0d, 0x12, 0x08, 0x09, 0x51, 0x2d, 0x5c, 0xe0,
	0x62, 0x6d, 0xed, 0xc1, 0x59, 0x65, 0xed, 0xb5, 0xd6, 0xe3, 0x92, 0xfc, 0x39, 0x7e, 0x1b, 0xf2,
	0x7a, 0x1d, 0x02, 0x9c, 0x76, 0xe7, 0xbd, 0x97, 0xf9, 0x66, 0xb2, 0x86, 0x47, 0xb2, 0x20, 0x34,
	0x85, 0x50, 0x51, 0x69, 0x34, 0xe9, 0x28, 0x15, 0x98, 0xeb, 0x62, 0x61, 0x0b, 0xe6, 0xb7, 0x55,
	0xf8, 0xcb, 0x83, 0xe1, 0x17, 0x34, 0xf7, 0x32, 0x41, 0x76, 0x01, 0xa7, 0xdb, 0x55, 0x15, 0xef,
	0x45, 0xae, 0x02, 0x6f, 0xe6, 0xcd, 0x47, 0x7c, 0xb8, 0x5d, 0x55, 0xdf, 0x44, 0xae, 0xd8, 0x33,
	0x38, 0x4f, 0x75, 0xb2, 0x45, 0xf3, 0x43, 0x2a, 0x8c, 0x09, 0x77, 0x14, 0x3c, 0xb0, 0x89, 0xe9,
	0x1f, 0xf9, 0x2b, 0xee, 0x88, 0x5d, 0x81, 0x9f, 0xeb, 0xba, 0xa0, 0x2a, 0xe8, 0xcd, 0x7a, 0xf3,
	0xf1, 0x72, 0xb2, 0x70, 0xd8, 0x4f, 0x8d, 0xca, 0x9d, 0xc9, 0x9e, 0xc0, 0xa0, 0x22, 0x2c, 0xab,
	0xa0, 0x6f, 0x53, 0xe3, 0x2e, 0xb5, 0xce, 0x53, 0xde, 0x3a, 0xec, 0x0a, 0xa6, 0xc7, 0x48, 0x91,
	0x05, 0x03, 0x4b, 0x9c, 0x1c, 0x11, 0x45, 0x16, 0x5e, 0x40, 0x6f, 0x9d, 0xa7, 0x8c, 0x41, 0x5f,
	0x98, 0xec, 0x3e, 0xf0, 0x66, 0xbd, 0xf9, 0x88, 0xdb, 0x7b, 0x78, 0x0b, 0x03, 0x4b, 0x65, 0x33,
	0xe8, 0x1b, 0x2c, 0xb5, 0x5d, 0x6a, 0xbc, 0x3c, 0xeb, 0x60, 0x1c, 0x4b, 0xcd, 0xad, 0xd3, 0xc0,
	0x12, 0x5d, 0x90, 0x90, 0x05, 0x9a, 0xb8, 0x14, 0xb4, 0x71, 0xeb, 0x4d, 0x0e, 0xea, 0xad, 0xa0,
	0x4d, 0xf8, 0x16, 0xfa, 0xcd, 0x8f, 0xd8, 0x73, 0x38, 0xcd, 0x24, 0xc5, 0x47, 0x4d, 0xcf, 0xbb,
	0xa6, 0xef, 0x25, 0x35, 0x91, 0x0f, 0x27, 0x7c, 0x98, 0xb5, 0xd7, 0x9b, 0x31, 0x8c, 0x9a, 0x64,
	0x4c, 0xfb, 0x12, 0xc3, 0x39, 0x0c, 0x5d, 0x84, 0x3d, 0x06, 0x50, 0x3a, 0x11, 0xaa, 0x05, 0xb6,
	0xff, 0xf8, 0xc8, 0x2a, 0x16, 0xb6, 0x02, 0xff, 0x73, 0x4d, 0x65, 0x4d, 0xec, 0x21, 0xf8, 0x15,
	0xa5, 0xba, 0x26, 0x1b, 0x3a, 0xe3, 0xae, 0x72, 0x3a, 0x1a, 0x63, 0xa7, 0x6d, 0x75, 0x34, 0x26,
	0x7c, 0x0d, 0x6c, 0x6d, 0x50, 0x10, 0xba, 0x97, 0xe5, 0x58, 0xaa, 0x3d, 0x7b, 0x0a, 0xbe, 0xb6,
	0xfd, 0xdc, 0xc8, 0xd3, 0x6e, 0xe4, 0x96, 0xc2, 0x9d, 0xbb, 0xfc, 0x08, 0xfe, 0x3b, 0x6b, 0xb0,
	0x37, 0x30, 0xf9, 0xab, 0x0f, 0x3b, 0x6c, 0xe9, 0x84, 0xcb, 0xcb, 0xc3, 0xc3, 0xfd, 0xc7, 0x0b,
	0x4f, 0x5e, 0x78, 0x37, 0xd7, 0xdf, 0x5f, 0x66, 0x92, 0x36, 0xf5, 0xdd, 0x22, 0xd1, 0x79, 0xf4,
	0x53, 0x16, 0x69, 0x2e, 0x95, 0xc2, 0x22, 0x8b, 0x48, 0x2a, 0x8a, 0xfe, 0xf9, 0x42, 0x5f, 0xd9,
	0xe3, 0xce, 0xb7, 0xc7, 0xf5, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x55, 0xbd, 0x30, 0x68, 0xc1,
	0x02, 0x00, 0x00,
}
