// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto/daemon.proto

package proto // import "github.com/windmilleng/tilt/internal/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Service struct {
	K8SYaml              string   `protobuf:"bytes,1,opt,name=k8s_yaml,json=k8sYaml,proto3" json:"k8s_yaml,omitempty"`
	DockerfileText       string   `protobuf:"bytes,2,opt,name=dockerfile_text,json=dockerfileText,proto3" json:"dockerfile_text,omitempty"`
	Mounts               []*Mount `protobuf:"bytes,3,rep,name=mounts,proto3" json:"mounts,omitempty"`
	Steps                []*Cmd   `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	DockerfileTag        string   `protobuf:"bytes,5,opt,name=dockerfile_tag,json=dockerfileTag,proto3" json:"dockerfile_tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_1be4cc8f100d9609, []int{0}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (dst *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(dst, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetK8SYaml() string {
	if m != nil {
		return m.K8SYaml
	}
	return ""
}

func (m *Service) GetDockerfileText() string {
	if m != nil {
		return m.DockerfileText
	}
	return ""
}

func (m *Service) GetMounts() []*Mount {
	if m != nil {
		return m.Mounts
	}
	return nil
}

func (m *Service) GetSteps() []*Cmd {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *Service) GetDockerfileTag() string {
	if m != nil {
		return m.DockerfileTag
	}
	return ""
}

type Debug struct {
	Mode                 bool     `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Debug) Reset()         { *m = Debug{} }
func (m *Debug) String() string { return proto.CompactTextString(m) }
func (*Debug) ProtoMessage()    {}
func (*Debug) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_1be4cc8f100d9609, []int{1}
}
func (m *Debug) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Debug.Unmarshal(m, b)
}
func (m *Debug) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Debug.Marshal(b, m, deterministic)
}
func (dst *Debug) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Debug.Merge(dst, src)
}
func (m *Debug) XXX_Size() int {
	return xxx_messageInfo_Debug.Size(m)
}
func (m *Debug) XXX_DiscardUnknown() {
	xxx_messageInfo_Debug.DiscardUnknown(m)
}

var xxx_messageInfo_Debug proto.InternalMessageInfo

func (m *Debug) GetMode() bool {
	if m != nil {
		return m.Mode
	}
	return false
}

type Cmd struct {
	Argv                 []string `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cmd) Reset()         { *m = Cmd{} }
func (m *Cmd) String() string { return proto.CompactTextString(m) }
func (*Cmd) ProtoMessage()    {}
func (*Cmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_1be4cc8f100d9609, []int{2}
}
func (m *Cmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cmd.Unmarshal(m, b)
}
func (m *Cmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cmd.Marshal(b, m, deterministic)
}
func (dst *Cmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cmd.Merge(dst, src)
}
func (m *Cmd) XXX_Size() int {
	return xxx_messageInfo_Cmd.Size(m)
}
func (m *Cmd) XXX_DiscardUnknown() {
	xxx_messageInfo_Cmd.DiscardUnknown(m)
}

var xxx_messageInfo_Cmd proto.InternalMessageInfo

func (m *Cmd) GetArgv() []string {
	if m != nil {
		return m.Argv
	}
	return nil
}

type Mount struct {
	Repo                 *Repo    `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	ContainerPath        string   `protobuf:"bytes,2,opt,name=container_path,json=containerPath,proto3" json:"container_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mount) Reset()         { *m = Mount{} }
func (m *Mount) String() string { return proto.CompactTextString(m) }
func (*Mount) ProtoMessage()    {}
func (*Mount) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_1be4cc8f100d9609, []int{3}
}
func (m *Mount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mount.Unmarshal(m, b)
}
func (m *Mount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mount.Marshal(b, m, deterministic)
}
func (dst *Mount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mount.Merge(dst, src)
}
func (m *Mount) XXX_Size() int {
	return xxx_messageInfo_Mount.Size(m)
}
func (m *Mount) XXX_DiscardUnknown() {
	xxx_messageInfo_Mount.DiscardUnknown(m)
}

var xxx_messageInfo_Mount proto.InternalMessageInfo

func (m *Mount) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

func (m *Mount) GetContainerPath() string {
	if m != nil {
		return m.ContainerPath
	}
	return ""
}

type Repo struct {
	// Types that are valid to be assigned to RepoType:
	//	*Repo_GitRepo
	RepoType             isRepo_RepoType `protobuf_oneof:"repo_type"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Repo) Reset()         { *m = Repo{} }
func (m *Repo) String() string { return proto.CompactTextString(m) }
func (*Repo) ProtoMessage()    {}
func (*Repo) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_1be4cc8f100d9609, []int{4}
}
func (m *Repo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repo.Unmarshal(m, b)
}
func (m *Repo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repo.Marshal(b, m, deterministic)
}
func (dst *Repo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repo.Merge(dst, src)
}
func (m *Repo) XXX_Size() int {
	return xxx_messageInfo_Repo.Size(m)
}
func (m *Repo) XXX_DiscardUnknown() {
	xxx_messageInfo_Repo.DiscardUnknown(m)
}

var xxx_messageInfo_Repo proto.InternalMessageInfo

type isRepo_RepoType interface {
	isRepo_RepoType()
}

type Repo_GitRepo struct {
	GitRepo *GitRepo `protobuf:"bytes,1,opt,name=git_repo,json=gitRepo,proto3,oneof"`
}

func (*Repo_GitRepo) isRepo_RepoType() {}

func (m *Repo) GetRepoType() isRepo_RepoType {
	if m != nil {
		return m.RepoType
	}
	return nil
}

func (m *Repo) GetGitRepo() *GitRepo {
	if x, ok := m.GetRepoType().(*Repo_GitRepo); ok {
		return x.GitRepo
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Repo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Repo_OneofMarshaler, _Repo_OneofUnmarshaler, _Repo_OneofSizer, []interface{}{
		(*Repo_GitRepo)(nil),
	}
}

func _Repo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Repo)
	// repo_type
	switch x := m.RepoType.(type) {
	case *Repo_GitRepo:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GitRepo); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Repo.RepoType has unexpected type %T", x)
	}
	return nil
}

func _Repo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Repo)
	switch tag {
	case 1: // repo_type.git_repo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GitRepo)
		err := b.DecodeMessage(msg)
		m.RepoType = &Repo_GitRepo{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Repo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Repo)
	// repo_type
	switch x := m.RepoType.(type) {
	case *Repo_GitRepo:
		s := proto.Size(x.GitRepo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GitRepo struct {
	LocalPath            string   `protobuf:"bytes,1,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GitRepo) Reset()         { *m = GitRepo{} }
func (m *GitRepo) String() string { return proto.CompactTextString(m) }
func (*GitRepo) ProtoMessage()    {}
func (*GitRepo) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_1be4cc8f100d9609, []int{5}
}
func (m *GitRepo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GitRepo.Unmarshal(m, b)
}
func (m *GitRepo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GitRepo.Marshal(b, m, deterministic)
}
func (dst *GitRepo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GitRepo.Merge(dst, src)
}
func (m *GitRepo) XXX_Size() int {
	return xxx_messageInfo_GitRepo.Size(m)
}
func (m *GitRepo) XXX_DiscardUnknown() {
	xxx_messageInfo_GitRepo.DiscardUnknown(m)
}

var xxx_messageInfo_GitRepo proto.InternalMessageInfo

func (m *GitRepo) GetLocalPath() string {
	if m != nil {
		return m.LocalPath
	}
	return ""
}

type CreateServiceReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServiceReply) Reset()         { *m = CreateServiceReply{} }
func (m *CreateServiceReply) String() string { return proto.CompactTextString(m) }
func (*CreateServiceReply) ProtoMessage()    {}
func (*CreateServiceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_1be4cc8f100d9609, []int{6}
}
func (m *CreateServiceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceReply.Unmarshal(m, b)
}
func (m *CreateServiceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceReply.Marshal(b, m, deterministic)
}
func (dst *CreateServiceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceReply.Merge(dst, src)
}
func (m *CreateServiceReply) XXX_Size() int {
	return xxx_messageInfo_CreateServiceReply.Size(m)
}
func (m *CreateServiceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceReply proto.InternalMessageInfo

type DebugReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebugReply) Reset()         { *m = DebugReply{} }
func (m *DebugReply) String() string { return proto.CompactTextString(m) }
func (*DebugReply) ProtoMessage()    {}
func (*DebugReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_1be4cc8f100d9609, []int{7}
}
func (m *DebugReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugReply.Unmarshal(m, b)
}
func (m *DebugReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugReply.Marshal(b, m, deterministic)
}
func (dst *DebugReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugReply.Merge(dst, src)
}
func (m *DebugReply) XXX_Size() int {
	return xxx_messageInfo_DebugReply.Size(m)
}
func (m *DebugReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugReply.DiscardUnknown(m)
}

var xxx_messageInfo_DebugReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Service)(nil), "daemon.Service")
	proto.RegisterType((*Debug)(nil), "daemon.Debug")
	proto.RegisterType((*Cmd)(nil), "daemon.Cmd")
	proto.RegisterType((*Mount)(nil), "daemon.Mount")
	proto.RegisterType((*Repo)(nil), "daemon.Repo")
	proto.RegisterType((*GitRepo)(nil), "daemon.GitRepo")
	proto.RegisterType((*CreateServiceReply)(nil), "daemon.CreateServiceReply")
	proto.RegisterType((*DebugReply)(nil), "daemon.DebugReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DaemonClient is the client API for Daemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaemonClient interface {
	CreateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*CreateServiceReply, error)
	SetDebug(ctx context.Context, in *Debug, opts ...grpc.CallOption) (*DebugReply, error)
}

type daemonClient struct {
	cc *grpc.ClientConn
}

func NewDaemonClient(cc *grpc.ClientConn) DaemonClient {
	return &daemonClient{cc}
}

func (c *daemonClient) CreateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*CreateServiceReply, error) {
	out := new(CreateServiceReply)
	err := c.cc.Invoke(ctx, "/daemon.Daemon/CreateService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SetDebug(ctx context.Context, in *Debug, opts ...grpc.CallOption) (*DebugReply, error) {
	out := new(DebugReply)
	err := c.cc.Invoke(ctx, "/daemon.Daemon/SetDebug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServer is the server API for Daemon service.
type DaemonServer interface {
	CreateService(context.Context, *Service) (*CreateServiceReply, error)
	SetDebug(context.Context, *Debug) (*DebugReply, error)
}

func RegisterDaemonServer(s *grpc.Server, srv DaemonServer) {
	s.RegisterService(&_Daemon_serviceDesc, srv)
}

func _Daemon_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.Daemon/CreateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).CreateService(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SetDebug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Debug)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SetDebug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.Daemon/SetDebug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SetDebug(ctx, req.(*Debug))
	}
	return interceptor(ctx, in, info, handler)
}

var _Daemon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "daemon.Daemon",
	HandlerType: (*DaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateService",
			Handler:    _Daemon_CreateService_Handler,
		},
		{
			MethodName: "SetDebug",
			Handler:    _Daemon_SetDebug_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/daemon.proto",
}

func init() { proto.RegisterFile("internal/proto/daemon.proto", fileDescriptor_daemon_1be4cc8f100d9609) }

var fileDescriptor_daemon_1be4cc8f100d9609 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0x8d, 0xeb, 0xef, 0x71, 0x9c, 0xc0, 0xd2, 0x83, 0xe2, 0x50, 0x70, 0x05, 0xa1, 0x3e, 0x14,
	0xab, 0xb8, 0x97, 0x40, 0xa1, 0xd0, 0x38, 0xd0, 0x5e, 0x0a, 0x61, 0xd3, 0x4b, 0x7b, 0x11, 0x6b,
	0x69, 0x2a, 0x2f, 0xde, 0xd5, 0x8a, 0xd5, 0x38, 0x8d, 0xff, 0x5c, 0x7f, 0x5b, 0xd1, 0x48, 0x76,
	0x6d, 0x72, 0x91, 0xf6, 0xbd, 0x79, 0x33, 0xef, 0x69, 0x47, 0x70, 0xad, 0x73, 0x42, 0x9f, 0x2b,
	0x13, 0x15, 0xde, 0x91, 0x8b, 0x52, 0x85, 0xd6, 0xe5, 0x73, 0x06, 0xa2, 0x57, 0xa3, 0xf0, 0x6f,
	0x0b, 0xfa, 0x8f, 0xe8, 0x9f, 0x74, 0x82, 0xe2, 0x0a, 0x06, 0x9b, 0xdb, 0x32, 0xde, 0x29, 0x6b,
	0x82, 0xd6, 0xb4, 0x35, 0x1b, 0xca, 0xfe, 0xe6, 0xb6, 0xfc, 0xa9, 0xac, 0x11, 0xef, 0xe0, 0x32,
	0x75, 0xc9, 0x06, 0xfd, 0x6f, 0x6d, 0x30, 0x26, 0x7c, 0xa6, 0xe0, 0x15, 0x2b, 0x2e, 0xfe, 0xd3,
	0x3f, 0xf0, 0x99, 0xc4, 0x0d, 0xf4, 0xac, 0xdb, 0xe6, 0x54, 0x06, 0xed, 0x69, 0x7b, 0x36, 0x5a,
	0x8c, 0xe7, 0x8d, 0xed, 0xf7, 0x8a, 0x95, 0x4d, 0x51, 0xbc, 0x85, 0x6e, 0x49, 0x58, 0x94, 0x41,
	0x87, 0x55, 0xa3, 0xbd, 0x6a, 0x69, 0x53, 0x59, 0x57, 0xc4, 0x0d, 0x5c, 0x1c, 0x5b, 0xaa, 0x2c,
	0xe8, 0xb2, 0xe3, 0xf8, 0xc8, 0x51, 0x65, 0xe1, 0x35, 0x74, 0xef, 0x71, 0xb5, 0xcd, 0x84, 0x80,
	0x8e, 0x75, 0x29, 0x72, 0xf2, 0x81, 0xe4, 0x73, 0x78, 0x05, 0xed, 0xa5, 0x4d, 0xab, 0x92, 0xf2,
	0xd9, 0x53, 0xd0, 0x9a, 0xb6, 0x67, 0x43, 0xc9, 0xe7, 0xf0, 0x01, 0xba, 0x1c, 0x49, 0x4c, 0xa1,
	0xe3, 0xb1, 0x70, 0xdc, 0x37, 0x5a, 0x9c, 0xef, 0x93, 0x48, 0x2c, 0x9c, 0xe4, 0x4a, 0x95, 0x24,
	0x71, 0x39, 0x29, 0x9d, 0xa3, 0x8f, 0x0b, 0x45, 0xeb, 0xe6, 0xdb, 0xc7, 0x07, 0xf6, 0x41, 0xd1,
	0x3a, 0xfc, 0x02, 0x9d, 0xaa, 0x49, 0xbc, 0x87, 0x41, 0xa6, 0x29, 0x3e, 0x1a, 0x7a, 0xb9, 0x1f,
	0xfa, 0x55, 0x53, 0x25, 0xf9, 0x76, 0x26, 0xfb, 0x59, 0x7d, 0xbc, 0x1b, 0xc1, 0xb0, 0x52, 0xc6,
	0xb4, 0x2b, 0x30, 0x9c, 0x41, 0xbf, 0x91, 0x88, 0x37, 0x00, 0xc6, 0x25, 0xca, 0xd4, 0x86, 0xf5,
	0x3a, 0x86, 0xcc, 0xb0, 0xd9, 0x6b, 0x10, 0x4b, 0x8f, 0x8a, 0xb0, 0x59, 0x9e, 0xc4, 0xc2, 0xec,
	0xc2, 0x73, 0x00, 0xbe, 0x0c, 0x46, 0x8b, 0x1d, 0xf4, 0xee, 0xd9, 0x57, 0x7c, 0x86, 0xf1, 0x89,
	0x5a, 0x1c, 0x12, 0x35, 0xc4, 0x64, 0x72, 0xd8, 0xc0, 0xcb, 0xa9, 0x67, 0x22, 0x82, 0xc1, 0x23,
	0x52, 0x7d, 0xcf, 0x87, 0x8d, 0x32, 0x9c, 0x88, 0x13, 0xd8, 0x34, 0xdc, 0x2d, 0x7e, 0x7d, 0xc8,
	0x34, 0xad, 0xb7, 0xab, 0x79, 0xe2, 0x6c, 0xf4, 0x47, 0xe7, 0xa9, 0xd5, 0xc6, 0x60, 0x9e, 0x45,
	0xa4, 0x0d, 0x45, 0xa7, 0x7f, 0xe6, 0x27, 0x7e, 0xae, 0x7a, 0xfc, 0xfa, 0xf8, 0x2f, 0x00, 0x00,
	0xff, 0xff, 0x66, 0x61, 0x97, 0xc4, 0xb8, 0x02, 0x00, 0x00,
}
