version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/**"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "gomod"
    directory: "/**"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
