apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-update
  namespace: tilt-integration
  labels:
    app: live-update
spec:
  selector:
    matchLabels:
      app: live-update
  template:
    metadata:
      labels:
        app: live-update
    spec:
      containers:
      - name: live-update
        image: gcr.io/windmill-test-containers/integration/live-update
        command: ["/go/bin/live_update"]
        ports:
        - containerPort: 8000
