# -*- mode: Python -*-

# If you get push errors, you can change the default_registry.
# Create tilt_option.json with contents: {"default_registry": "gcr.io/my-personal-project"}
# (with your registry inserted). tilt_option.json is gitignore'd, unlike Tiltfile
default_registry(read_json('tilt_option.json', {})
                 .get('default_registry', 'gcr.io/windmill-test-containers/servantes'))

docker_build('gcr.io/windmill-test-containers/integration/live-update', '.')
live_update(
    'gcr.io/windmill-test-containers/integration/live-update',
    [
        sync('.', '/go/src/github.com/windmilleng/integration/live_update'),
        run('go install github.com/windmilleng/integration/live_update'),
        restart_container(),
    ]
)

k8s_resource('live-update', 'deploy.yaml', port_forwards=8100)
