# options for analysis running
run:
  # by default isn't set. If set we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  # If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores
  # the dependency descriptions in go.mod.
  modules-download-mode: vendor
  build-tags:
    - integration

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

# all available settings of specific linters
linters-settings:
  errcheck:
    # report about not checking of errors in type assetions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: false

    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: false
  govet:
    settings:
      printf:
        funcs:
          - Verbosef
          - Infof
          - Debugf
          - PrintColorf
  goimports:
    local-prefixes: github.com/windmilleng/tilt
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
    ignore-words:
      - servantes
linters:
  disable-all: true
  enable:
    - errcheck
    - megacheck
    - govet
    - goimports
    - structcheck
    - ineffassign
    - misspell
issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019:"
    - linters:
        - gosimple
      text: "S1008:"
    - linters:
        - staticcheck
      text: "is unused"
    - linters:
        - unused
      text: "is unused"



