# options for analysis running
run:
  timeout: 10m
  go: "1.23"
  exclude-files:
    - "zz_generated.*\\.go$"
    - "vendored_openapi\\.go$"
  allow-parallel-runners: true
  modules-download-mode: vendor
  build-tags:
    - integration

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  formats:
  - format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

# all available settings of specific linters
linters-settings:
  errcheck:
    # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: false

    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: false
  govet:
    settings:
      printf:
        funcs:
          - Verbosef
          - Infof
          - Debugf
          - PrintColorf
  goimports:
    local-prefixes: github.com/tilt-dev
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
    ignore-words:
      - servantes
      - cancelled # British spelling used in Kubernetes code

linters:
  disable-all: true
  enable:
    - copyloopvar
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - misspell
    - unconvert
    - unused

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019:"
    - linters:
        - gosimple
      text: "S1008:"
    - path: _test\.go
      linters:
        - errcheck
    - path: types.go
      linters:
        - unconvert
