project_name: tilt
before:
  hooks:
    - ./scripts/upload-assets.py latest
builds:
- env:
  main: ./cmd/tilt/main.go
  flags:
  - -tags=osusergo
  - -mod=vendor
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
archives:
- name_template: "{{ .ProjectName }}.{{ .Version }}.{{ .Os }}.{{ .Arch }}"
  replacements:
    windows: windows
    darwin: mac
    linux: linux
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- github:
    owner: tilt-dev
    name: homebrew-tap
  commit_author:
    name: Tilt Dev
    email: hi@tilt.dev
  url_template: "http://github.com/tilt-dev/tilt/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  homepage: "https://tilt.dev/"
  description: "Tilt powers multi-service developments for teams that deploy to Kubernetes."
  test: |
    system "#{bin}/tilt version"
dockers:
- image_templates:
    - "tiltdev/tilt"
    - "tiltdev/tilt:{{ .Tag }}"
  dockerfile: scripts/goreleaser.Dockerfile
scoop:
  url_template: "http://github.com/tilt-dev/tilt/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  bucket:
    owner: tilt-dev
    name: scoop-bucket
  commit_author:
    name: Tilt Dev
    email: hi@tilt.dev
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://tilt.dev/"
  description: "Tilt powers multi-service developments for teams that deploy to Kubernetes."
  license: Apache-2.0
  
# Uncomment these lines if you want to experiment with other
# parts of the release process without releasing new binaries.
# release:
#  disable: true
