project_name: tilt
builds:
- main: ./cmd/tilt/main.go
  id: tilt-darwin
  flags:
  - -tags=osusergo
  - -mod=vendor
  goos:
  - darwin
  goarch:
  - amd64
  - arm64
  env:
  # clang is a cross-compiler by default, so the same CC/CXX works
  # for arm64 (M1) & amd64 (Intel) builds
  - CGO_ENABLED=1
  - CC=o64h-clang
  - CXX=o64h-clang++
- main: ./cmd/tilt/main.go
  id: tilt-linux-arm64
  flags:
    - -tags=osusergo
    - -mod=vendor
  goos:
    - linux
  goarch:
    - arm64
  env:
    - CGO_ENABLED=1
    - CC=aarch64-linux-gnu-gcc
    - CXX=aarch64-linux-gnu-g++
- main: ./cmd/tilt/main.go
  id: tilt-linux-arm
  flags:
    - -tags=osusergo
    - -mod=vendor
  goos:
    - linux
  goarch:
    - arm
  env:
    - CGO_ENABLED=1
    - CC=arm-linux-gnueabi-gcc
    - CXX=arm-linux-gnueabi-g++
- main: ./cmd/tilt/main.go
  id: tilt-linux-amd64
  flags:
    - -tags=osusergo
    - -mod=vendor
  goos:
    - linux
  goarch:
    - amd64
  env:
    - CGO_ENABLED=1
- main: ./cmd/tilt/main.go
  id: tilt-windows-amd64
  flags:
  - -tags=osusergo
  - -mod=vendor
  goos:
  - windows
  goarch:
  - amd64
  env:
    - CGO_ENABLED=1
    - CGO_LDFLAGS=-static
    - CC=x86_64-w64-mingw32-gcc
    - CXX=x86_64-w64-mingw32-g++
archives:
- name_template: "{{ .ProjectName }}.{{ .Version }}.{{ .Os }}.{{ .Arch }}"
  replacements:
    windows: windows
    darwin: mac
    linux: linux
    386: i386
    amd64: x86_64
    arm: arm
    arm64: arm64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
  
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^docs?:'
    - '^tests?:'
    - '^cleanup:'
    - '^circleci:'
    - '^ci:'
    
brews:
- tap:
    owner: tilt-dev
    name: homebrew-tap
  commit_author:
    name: Tilt Dev
    email: hi@tilt.dev
  url_template: "https://github.com/tilt-dev/tilt/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  homepage: "https://tilt.dev/"
  description: "A dev environment as code for microservice apps"
  install: |
    bin.install "tilt"
    
    # Install bash completion
    output = Utils.safe_popen_read("#{bin}/tilt", "completion", "bash")
    (bash_completion/"tilt").write output

    # Install zsh completion
    output = Utils.safe_popen_read("#{bin}/tilt", "completion", "zsh")
    (zsh_completion/"_tilt").write output

    # Install fish completion
    output = Utils.safe_popen_read("#{bin}/tilt", "completion", "fish")
    (fish_completion/"tilt.fish").write output
  test: |
    system "#{bin}/tilt version"
    system "#{bin}/tilt verify-install"
dockers:
- goos: linux
  goarch: amd64
  image_templates:
    - "tiltdev/tilt:{{ .Tag }}-amd64"
  dockerfile: scripts/tilt.Dockerfile
  use: buildx
  build_flag_templates:
  - "--platform=linux/amd64"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.description={{ .ProjectName }}"
  - "--label=org.opencontainers.image.url=https://github.com/tilt-dev/{{ .ProjectName }}"
  - "--label=org.opencontainers.image.source=https://github.com/tilt-dev/{{ .ProjectName }}"
  - "--label=org.opencontainers.image.version={{ .Version }}"
  - "--label=org.opencontainers.image.created={{ .Timestamp }}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.licenses=Apache-2.0"
- goos: linux
  goarch: arm64
  goarm: ''
  image_templates:
    - "tiltdev/tilt:{{ .Tag }}-arm64"
  dockerfile: scripts/tilt.Dockerfile
  use: buildx
  build_flag_templates:
  - "--platform=linux/arm64"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.description={{ .ProjectName }}"
  - "--label=org.opencontainers.image.url=https://github.com/tilt-dev/{{ .ProjectName }}"
  - "--label=org.opencontainers.image.source=https://github.com/tilt-dev/{{ .ProjectName }}"
  - "--label=org.opencontainers.image.version={{ .Version }}"
  - "--label=org.opencontainers.image.created={{ .Timestamp }}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.licenses=Apache-2.0"
docker_manifests:
- name_template: tiltdev/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - tiltdev/{{ .ProjectName }}:{{ .Version }}-amd64
  - tiltdev/{{ .ProjectName }}:{{ .Version }}-arm64
- name_template: tiltdev/{{ .ProjectName }}:latest
  image_templates:
  - tiltdev/{{ .ProjectName }}:{{ .Version }}-amd64
  - tiltdev/{{ .ProjectName }}:{{ .Version }}-arm64
scoop:
  url_template: "https://github.com/tilt-dev/tilt/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  bucket:
    owner: tilt-dev
    name: scoop-bucket
  commit_author:
    name: Tilt Dev
    email: hi@tilt.dev
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://tilt.dev/"
  description: "A dev environment as code for microservice apps"
  license: Apache-2.0
release:
  header: |
    [Install Tilt](https://docs.tilt.dev/install.html) ⬇️ | [Upgrade Tilt](https://docs.tilt.dev/upgrade.html) ⬆️ | [Tilt Extensions](https://github.com/tilt-dev/tilt-extensions/) 🧰

    ## Notable Changes

    TBD

# Uncomment these lines if you want to experiment with other
# parts of the release process without releasing new binaries.
# release:
#  disable: true
