project_name: tilt
before:
  hooks:
    - ./scripts/upload-assets.py latest
builds:
- env:
  main: ./cmd/tilt/main.go
  goos:
  - linux
  - darwin
  - windows
  # Cross-compiling darwin is a pain due to fsevents,
  # and we don't expect darwin/386 users anyway.
  ignore:
  - goos: darwin
    goarch: 386
  - goos: windows
    goarch: 386
archive:
  name_template: "{{ .ProjectName }}.{{ .Version }}.{{ .Os }}.{{ .Arch }}"
  replacements:
    windows: windows_ALPHA
    darwin: mac
    linux: linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: windmilleng
    name: homebrew-tap
  commit_author:
    name: Windmill Engineering
    email: hi@windmill.engineering
  url_template: "http://github.com/windmilleng/tilt/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  homepage: "https://tilt.build/"
  description: "Local Kubernetes development with no stress"
  test: |
    system "#{bin}/tilt version"

# Uncomment these lines if you want to experiment with other
# parts of the release process without releasing new binaries.
# release:
#  disable: true
