project_name: tilt
builds:
- main: ./cmd/tilt/main.go
  id: tilt-darwin
  flags:
  - -tags=osusergo
  - -mod=vendor
  goos:
  - darwin
  goarch:
  - amd64
  - arm64
  env:
  # Compiles against the MacOS FSEvents system libraries.
  - CGO_ENABLED=1
  - CC=/osxcross/target/bin/x86_64h-apple-darwin20.2-clang
- main: ./cmd/tilt/main.go
  id: tilt
  flags:
  - -tags=osusergo
  - -mod=vendor
  goos:
  - linux
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  env:
  - CGO_ENABLED=0
archives:
- name_template: "{{ .ProjectName }}.{{ .Version }}.{{ .Os }}.{{ .Arch }}"
  replacements:
    windows: windows
    darwin: mac
    linux: linux
    386: i386
    amd64: x86_64
    arm: arm_ALPHA
    arm64: arm64_ALPHA
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs?:'
    - '^tests?:'
    - '^cleanup:'
    - '^circleci:'
    - '^ci:'
brews:
- tap:
    owner: tilt-dev
    name: homebrew-tap
  commit_author:
    name: Tilt Dev
    email: hi@tilt.dev
  url_template: "https://github.com/tilt-dev/tilt/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  homepage: "https://tilt.dev/"
  description: "Tilt powers multi-service developments for teams that deploy to Kubernetes."
  test: |
    system "#{bin}/tilt version"
    system "#{bin}/tilt verify-install"
dockers:
- image_templates:
    - "tiltdev/tilt"
    - "tiltdev/tilt:{{ .Tag }}"
  dockerfile: scripts/tilt.Dockerfile
scoop:
  url_template: "https://github.com/tilt-dev/tilt/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  bucket:
    owner: tilt-dev
    name: scoop-bucket
  commit_author:
    name: Tilt Dev
    email: hi@tilt.dev
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://tilt.dev/"
  description: "Tilt powers multi-service developments for teams that deploy to Kubernetes."
  license: Apache-2.0

# Uncomment these lines if you want to experiment with other
# parts of the release process without releasing new binaries.
# release:
#  disable: true
