builds:
- env:
  main: ./cmd/tilt/main.go
  goos:
  - linux
  - darwin
  # Cross-compiling darwin is a pain due to fsevents,
  # and we don't expect darwin/386 users anyway.
  ignore:
  - goos: darwin
    goarch: 386
archive:
  name_template: "{{ .ProjectName }}.{{ .Version }}.{{ .Os }}.{{ .Arch }}"
  replacements:
    darwin: mac
    linux: linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
