FROM python:3.7

RUN pip3 install sphinx==1.8.3 sphinx_rtd_theme==0.4.2 sphinx-autodoc-typehints==1.6.0 recommonmark==0.5.0

# Path a dumb bug in sphinx
# TODO(nick): fix this upstream
RUN sed -i -e "s/^.*rawcaption.*\$//" /usr/local/lib/python3.7/site-packages/sphinx/environment/adapters/toctree.py

RUN mkdir -p /src
WORKDIR /src

ADD docs .
RUN make html
WORKDIR _build/html
ENTRYPOINT python -m http.server 8000