FROM golang:1.12-alpine
RUN apk update
RUN apk add protobuf protobuf-dev git
RUN go get -u github.com/golang/protobuf/protoc-gen-go github.com/golang/protobuf/jsonpb github.com/golang/protobuf/proto github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway google.golang.org/grpc
RUN go get golang.org/x/tools/cmd/goimports
