apiVersion: extensions/v1beta1 # useful for testing old k8s versions
kind: Deployment
metadata:
  name: tilt-docserver
spec:
  template:
    metadata:
      labels:
        app: tilt-docserver
    spec:
      containers:
      - name: tilt-docserver
        image: gcr.io/windmill-public-containers/tilt-docserver
        ports:
        - containerPort: 8000