apiVersion: batch/v1
kind: Job
metadata:
  name: shortlived-pod-success
  namespace: tilt-integration
  labels:
    app: shortlived-pod-success
spec:
  template:
    metadata:
      labels:
        app: shortlived-pod-success
    spec:
      containers:
        - name: echohi
          image: alpine
          command: ["sh", "-c", "echo this is a successful job"]
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shortlived-pod-fail
  namespace: tilt-integration
  labels:
    app: shortlived-pod-fail
spec:
  template:
    metadata:
      labels:
        app: shortlived-pod-fail
    spec:
      containers:
        - name: echohi
          image: alpine
          command: ["sh", "-c", "echo this job will fail && false"]
      restartPolicy: Never
  backoffLimit: 0

