# -*- mode: Python -*-

# HACK: load namespaces on `tilt up` but not on `tilt down`
load_namespace = not str(local('echo $SKIP_NAMESPACE')).strip()
if load_namespace:
  k8s_yaml('../namespace.yaml')

default_registry(read_json('tilt_option.json', {})
                 .get('default_registry', 'gcr.io/windmill-test-containers/servantes'))

k8s_yaml('shortlived_pods.yaml')
