
# HACK: load namespaces on `tilt up` but not on `tilt down`
load_namespace = not str(local('echo $SKIP_NAMESPACE')).strip()
if load_namespace:
  k8s_yaml('../namespace.yaml')

repo = 'gcr.io/windmill-test-containers'
docker_build(repo + '/live-update-base-image-common', 'common')
docker_build(repo + '/live-update-base-image-app', 'app', live_update=[
  sync('common/', '/app/'),
])

k8s_yaml(['app.yaml'])
k8s_resource('live-update-base-image', new_name='regular', port_forwards='31000:8000')
