apiVersion: v1
kind: Namespace
metadata:
  name: tilt-integration
  labels:
    name: tilt-integration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oneup
  namespace: tilt-integration
  labels:
    app: oneup
spec:
  selector:
    matchLabels:
      app: oneup
  template:
    metadata:
      labels:
        app: oneup
    spec:
      containers:
      - name: oneup
        image: gcr.io/windmill-test-containers/integration/oneup
        command: ["/go/bin/oneup"]
        ports:
        - containerPort: 8000