# -*- mode: Python -*-

# Read an option from the file tilt_option.json
# Create this file with json like { "default_registry": "gcr.io/my-personal-project" }
# tilt_option.json is .gitignore'd, so you'll have a clean status
default_registry(read_json('tilt_option.json', {})
                 .get('default_registry', 'gcr.io/windmill-public-containers/servantes'))

docker_build('oneup', '.')
k8s_resource('oneup', 'oneup.yaml', port_forwards=8100)
