# Template should be populated using populate_config_template.py

apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: %(owner)s-synclet
  namespace: kube-system
  labels:
    app: synclet
    owner: %(owner)s
    environment: %(environment)s
spec:
  selector:
    matchLabels:
      app: synclet
      owner: %(owner)s
      environment: %(environment)s
  template:
    metadata:
      labels:
        app: synclet
        owner: %(owner)s
        environment: %(environment)s
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: synclet
        image: %(imgname)s
        imagePullPolicy: Always
        volumeMounts:
        - name: dockersocker
          mountPath: /var/run/docker.sock
        securityContext:
          privileged: true
      - image: docker.io/jaegertracing/jaeger-agent
        name: jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        args: ["--collector.host-port=jaeger-collector.default:14267"]
      volumes:
        - name: dockersocker
          hostPath:
            path: /var/run/docker.sock
