// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cli

import (
	context "context"
	build "github.com/windmilleng/tilt/internal/build"
	engine "github.com/windmilleng/tilt/internal/engine"
	image "github.com/windmilleng/tilt/internal/image"
	k8s "github.com/windmilleng/tilt/internal/k8s"
	model "github.com/windmilleng/tilt/internal/model"
	service "github.com/windmilleng/tilt/internal/service"
	dirs "github.com/windmilleng/wmclient/pkg/dirs"
)

// Injectors from wire.go:

func wireServiceCreator(ctx context.Context) (model.ServiceCreator, error) {
	env, err := k8s.DetectEnv()
	if err != nil {
		return nil, err
	}
	dockerCli, err := build.DefaultDockerClient(ctx, env)
	if err != nil {
		return nil, err
	}
	console := build.DefaultConsole()
	writer := build.DefaultOut()
	dockerImageBuilder := build.NewLocalDockerBuilder(dockerCli, console, writer)
	imageBuilder := build.DefaultBuilder(dockerImageBuilder)
	kubectlClient := k8s.NewKubectlClient(ctx, env)
	windmillDir, err := dirs.UseWindmillDir()
	if err != nil {
		return nil, err
	}
	imageHistory, err := image.NewImageHistory(ctx, windmillDir)
	if err != nil {
		return nil, err
	}
	buildAndDeployer, err := engine.NewLocalBuildAndDeployer(imageBuilder, kubectlClient, imageHistory, env)
	if err != nil {
		return nil, err
	}
	upper := engine.NewUpper(ctx, buildAndDeployer, kubectlClient)
	manager := service.ProvideMemoryManager()
	serviceCreator := provideServiceCreator(upper, manager)
	return serviceCreator, nil
}
