include('../Tiltfile')

custom_build(
    ref='nginx',
    # this is a hack that puts the builder into "live update only" mode
    command=':',
    deps=['./web', 'special.txt'],
    disable_push=True,
    skips_local_docker=True,
    live_update=[
        sync('./web/', '/usr/share/nginx/html/')
    ]
)

k8s_yaml('nginx.yaml')

k8s_resource('lu-only', port_forwards=['28195:80'])
