// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/windmilleng/tilt/internal/synclet/synclet.proto

package proto // import "github.com/windmilleng/tilt/internal/synclet/proto"

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogLevel int32

const (
	LogLevel_INFO    LogLevel = 0
	LogLevel_VERBOSE LogLevel = 1
	LogLevel_DEBUG   LogLevel = 2
)

var LogLevel_name = map[int32]string{
	0: "INFO",
	1: "VERBOSE",
	2: "DEBUG",
}
var LogLevel_value = map[string]int32{
	"INFO":    0,
	"VERBOSE": 1,
	"DEBUG":   2,
}

func (x LogLevel) String() string {
	return proto.EnumName(LogLevel_name, int32(x))
}
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_synclet_3d35d45a699da701, []int{0}
}

type Cmd struct {
	Argv                 []string `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cmd) Reset()         { *m = Cmd{} }
func (m *Cmd) String() string { return proto.CompactTextString(m) }
func (*Cmd) ProtoMessage()    {}
func (*Cmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_synclet_3d35d45a699da701, []int{0}
}
func (m *Cmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cmd.Unmarshal(m, b)
}
func (m *Cmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cmd.Marshal(b, m, deterministic)
}
func (dst *Cmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cmd.Merge(dst, src)
}
func (m *Cmd) XXX_Size() int {
	return xxx_messageInfo_Cmd.Size(m)
}
func (m *Cmd) XXX_DiscardUnknown() {
	xxx_messageInfo_Cmd.DiscardUnknown(m)
}

var xxx_messageInfo_Cmd proto.InternalMessageInfo

func (m *Cmd) GetArgv() []string {
	if m != nil {
		return m.Argv
	}
	return nil
}

type UpdateContainerRequest struct {
	ContainerId          string    `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	TarArchive           []byte    `protobuf:"bytes,2,opt,name=tar_archive,json=tarArchive,proto3" json:"tar_archive,omitempty"`
	FilesToDelete        []string  `protobuf:"bytes,3,rep,name=files_to_delete,json=filesToDelete,proto3" json:"files_to_delete,omitempty"`
	Commands             []*Cmd    `protobuf:"bytes,4,rep,name=commands,proto3" json:"commands,omitempty"`
	LogStyle             *LogStyle `protobuf:"bytes,5,opt,name=log_style,json=logStyle,proto3" json:"log_style,omitempty"`
	HotReload            bool      `protobuf:"varint,6,opt,name=hot_reload,json=hotReload,proto3" json:"hot_reload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateContainerRequest) Reset()         { *m = UpdateContainerRequest{} }
func (m *UpdateContainerRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateContainerRequest) ProtoMessage()    {}
func (*UpdateContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_synclet_3d35d45a699da701, []int{1}
}
func (m *UpdateContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContainerRequest.Unmarshal(m, b)
}
func (m *UpdateContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContainerRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContainerRequest.Merge(dst, src)
}
func (m *UpdateContainerRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateContainerRequest.Size(m)
}
func (m *UpdateContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContainerRequest proto.InternalMessageInfo

func (m *UpdateContainerRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *UpdateContainerRequest) GetTarArchive() []byte {
	if m != nil {
		return m.TarArchive
	}
	return nil
}

func (m *UpdateContainerRequest) GetFilesToDelete() []string {
	if m != nil {
		return m.FilesToDelete
	}
	return nil
}

func (m *UpdateContainerRequest) GetCommands() []*Cmd {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *UpdateContainerRequest) GetLogStyle() *LogStyle {
	if m != nil {
		return m.LogStyle
	}
	return nil
}

func (m *UpdateContainerRequest) GetHotReload() bool {
	if m != nil {
		return m.HotReload
	}
	return false
}

type LogMessage struct {
	Level                LogLevel `protobuf:"varint,1,opt,name=level,proto3,enum=synclet.LogLevel" json:"level,omitempty"`
	Message              []byte   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogMessage) Reset()         { *m = LogMessage{} }
func (m *LogMessage) String() string { return proto.CompactTextString(m) }
func (*LogMessage) ProtoMessage()    {}
func (*LogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_synclet_3d35d45a699da701, []int{2}
}
func (m *LogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogMessage.Unmarshal(m, b)
}
func (m *LogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogMessage.Marshal(b, m, deterministic)
}
func (dst *LogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogMessage.Merge(dst, src)
}
func (m *LogMessage) XXX_Size() int {
	return xxx_messageInfo_LogMessage.Size(m)
}
func (m *LogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LogMessage proto.InternalMessageInfo

func (m *LogMessage) GetLevel() LogLevel {
	if m != nil {
		return m.Level
	}
	return LogLevel_INFO
}

func (m *LogMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type FailedRunStep struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	ExitCode             int32    `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailedRunStep) Reset()         { *m = FailedRunStep{} }
func (m *FailedRunStep) String() string { return proto.CompactTextString(m) }
func (*FailedRunStep) ProtoMessage()    {}
func (*FailedRunStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_synclet_3d35d45a699da701, []int{3}
}
func (m *FailedRunStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailedRunStep.Unmarshal(m, b)
}
func (m *FailedRunStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailedRunStep.Marshal(b, m, deterministic)
}
func (dst *FailedRunStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailedRunStep.Merge(dst, src)
}
func (m *FailedRunStep) XXX_Size() int {
	return xxx_messageInfo_FailedRunStep.Size(m)
}
func (m *FailedRunStep) XXX_DiscardUnknown() {
	xxx_messageInfo_FailedRunStep.DiscardUnknown(m)
}

var xxx_messageInfo_FailedRunStep proto.InternalMessageInfo

func (m *FailedRunStep) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *FailedRunStep) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

type UpdateContainerReply struct {
	LogMessage *LogMessage `protobuf:"bytes,1,opt,name=log_message,json=logMessage,proto3" json:"log_message,omitempty"`
	// Contains info about run step failure (if any)
	FailedRunStep        *FailedRunStep `protobuf:"bytes,2,opt,name=failed_run_step,json=failedRunStep,proto3" json:"failed_run_step,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateContainerReply) Reset()         { *m = UpdateContainerReply{} }
func (m *UpdateContainerReply) String() string { return proto.CompactTextString(m) }
func (*UpdateContainerReply) ProtoMessage()    {}
func (*UpdateContainerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_synclet_3d35d45a699da701, []int{4}
}
func (m *UpdateContainerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContainerReply.Unmarshal(m, b)
}
func (m *UpdateContainerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContainerReply.Marshal(b, m, deterministic)
}
func (dst *UpdateContainerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContainerReply.Merge(dst, src)
}
func (m *UpdateContainerReply) XXX_Size() int {
	return xxx_messageInfo_UpdateContainerReply.Size(m)
}
func (m *UpdateContainerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContainerReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContainerReply proto.InternalMessageInfo

func (m *UpdateContainerReply) GetLogMessage() *LogMessage {
	if m != nil {
		return m.LogMessage
	}
	return nil
}

func (m *UpdateContainerReply) GetFailedRunStep() *FailedRunStep {
	if m != nil {
		return m.FailedRunStep
	}
	return nil
}

type LogStyle struct {
	ColorsEnabled        bool     `protobuf:"varint,1,opt,name=colors_enabled,json=colorsEnabled,proto3" json:"colors_enabled,omitempty"`
	Level                LogLevel `protobuf:"varint,2,opt,name=level,proto3,enum=synclet.LogLevel" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogStyle) Reset()         { *m = LogStyle{} }
func (m *LogStyle) String() string { return proto.CompactTextString(m) }
func (*LogStyle) ProtoMessage()    {}
func (*LogStyle) Descriptor() ([]byte, []int) {
	return fileDescriptor_synclet_3d35d45a699da701, []int{5}
}
func (m *LogStyle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogStyle.Unmarshal(m, b)
}
func (m *LogStyle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogStyle.Marshal(b, m, deterministic)
}
func (dst *LogStyle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogStyle.Merge(dst, src)
}
func (m *LogStyle) XXX_Size() int {
	return xxx_messageInfo_LogStyle.Size(m)
}
func (m *LogStyle) XXX_DiscardUnknown() {
	xxx_messageInfo_LogStyle.DiscardUnknown(m)
}

var xxx_messageInfo_LogStyle proto.InternalMessageInfo

func (m *LogStyle) GetColorsEnabled() bool {
	if m != nil {
		return m.ColorsEnabled
	}
	return false
}

func (m *LogStyle) GetLevel() LogLevel {
	if m != nil {
		return m.Level
	}
	return LogLevel_INFO
}

func init() {
	proto.RegisterType((*Cmd)(nil), "synclet.Cmd")
	proto.RegisterType((*UpdateContainerRequest)(nil), "synclet.UpdateContainerRequest")
	proto.RegisterType((*LogMessage)(nil), "synclet.LogMessage")
	proto.RegisterType((*FailedRunStep)(nil), "synclet.FailedRunStep")
	proto.RegisterType((*UpdateContainerReply)(nil), "synclet.UpdateContainerReply")
	proto.RegisterType((*LogStyle)(nil), "synclet.LogStyle")
	proto.RegisterEnum("synclet.LogLevel", LogLevel_name, LogLevel_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SyncletClient is the client API for Synclet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SyncletClient interface {
	// updates the specified container and then restarts it
	// (much functionality packed into one rpc to minimize latency)
	UpdateContainer(ctx context.Context, in *UpdateContainerRequest, opts ...grpc.CallOption) (Synclet_UpdateContainerClient, error)
}

type syncletClient struct {
	cc *grpc.ClientConn
}

func NewSyncletClient(cc *grpc.ClientConn) SyncletClient {
	return &syncletClient{cc}
}

func (c *syncletClient) UpdateContainer(ctx context.Context, in *UpdateContainerRequest, opts ...grpc.CallOption) (Synclet_UpdateContainerClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Synclet_serviceDesc.Streams[0], "/synclet.Synclet/UpdateContainer", opts...)
	if err != nil {
		return nil, err
	}
	x := &syncletUpdateContainerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Synclet_UpdateContainerClient interface {
	Recv() (*UpdateContainerReply, error)
	grpc.ClientStream
}

type syncletUpdateContainerClient struct {
	grpc.ClientStream
}

func (x *syncletUpdateContainerClient) Recv() (*UpdateContainerReply, error) {
	m := new(UpdateContainerReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SyncletServer is the server API for Synclet service.
type SyncletServer interface {
	// updates the specified container and then restarts it
	// (much functionality packed into one rpc to minimize latency)
	UpdateContainer(*UpdateContainerRequest, Synclet_UpdateContainerServer) error
}

func RegisterSyncletServer(s *grpc.Server, srv SyncletServer) {
	s.RegisterService(&_Synclet_serviceDesc, srv)
}

func _Synclet_UpdateContainer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpdateContainerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyncletServer).UpdateContainer(m, &syncletUpdateContainerServer{stream})
}

type Synclet_UpdateContainerServer interface {
	Send(*UpdateContainerReply) error
	grpc.ServerStream
}

type syncletUpdateContainerServer struct {
	grpc.ServerStream
}

func (x *syncletUpdateContainerServer) Send(m *UpdateContainerReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Synclet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "synclet.Synclet",
	HandlerType: (*SyncletServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdateContainer",
			Handler:       _Synclet_UpdateContainer_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/windmilleng/tilt/internal/synclet/synclet.proto",
}

func init() {
	proto.RegisterFile("github.com/windmilleng/tilt/internal/synclet/synclet.proto", fileDescriptor_synclet_3d35d45a699da701)
}

var fileDescriptor_synclet_3d35d45a699da701 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x97, 0x75, 0x5d, 0x93, 0xcb, 0xba, 0x15, 0x83, 0xa6, 0x00, 0x9a, 0x16, 0x22, 0x01,
	0x11, 0x42, 0x2d, 0x2a, 0x3c, 0xa0, 0x21, 0x4d, 0x62, 0x5d, 0x87, 0x26, 0x15, 0x2a, 0xb9, 0x94,
	0x87, 0xbd, 0x04, 0x37, 0xbe, 0xa6, 0x91, 0x9c, 0x38, 0x24, 0x6e, 0xa1, 0xff, 0x03, 0xff, 0x32,
	0x12, 0xaa, 0xd3, 0x74, 0x1b, 0xbf, 0x24, 0x5e, 0xea, 0xbb, 0xcf, 0xf9, 0x7e, 0x7c, 0xaf, 0x31,
	0x9c, 0x44, 0xb1, 0x9a, 0xcd, 0x27, 0xed, 0x50, 0x26, 0x9d, 0xaf, 0x71, 0xca, 0x93, 0x58, 0x08,
	0x4c, 0xa3, 0x8e, 0x8a, 0x85, 0xea, 0xc4, 0xa9, 0xc2, 0x3c, 0x65, 0xa2, 0x53, 0x2c, 0xd3, 0x50,
	0xa0, 0xaa, 0xce, 0x76, 0x96, 0x4b, 0x25, 0x49, 0x63, 0xed, 0x7a, 0xf7, 0xa1, 0xd6, 0x4b, 0x38,
	0x21, 0xb0, 0xc3, 0xf2, 0x68, 0xe1, 0x18, 0x6e, 0xcd, 0xb7, 0xa8, 0xb6, 0xbd, 0x1f, 0x06, 0x1c,
	0x8e, 0x33, 0xce, 0x14, 0xf6, 0x64, 0xaa, 0x58, 0x9c, 0x62, 0x4e, 0xf1, 0xcb, 0x1c, 0x0b, 0x45,
	0x1e, 0xc1, 0x5e, 0x58, 0xb1, 0x20, 0xe6, 0x8e, 0xe1, 0x1a, 0xbe, 0x45, 0xed, 0x0d, 0xbb, 0xe4,
	0xe4, 0x18, 0x6c, 0xc5, 0xf2, 0x80, 0xe5, 0xe1, 0x2c, 0x5e, 0xa0, 0xb3, 0xed, 0x1a, 0xfe, 0x1e,
	0x05, 0xc5, 0xf2, 0xb7, 0x25, 0x21, 0x4f, 0xe0, 0x60, 0x1a, 0x0b, 0x2c, 0x02, 0x25, 0x03, 0x8e,
	0x02, 0x15, 0x3a, 0x35, 0xdd, 0xbd, 0xa9, 0xf1, 0x47, 0x79, 0xae, 0x21, 0xf1, 0xc1, 0x0c, 0x65,
	0x92, 0xb0, 0x94, 0x17, 0xce, 0x8e, 0x5b, 0xf3, 0xed, 0xee, 0x5e, 0xbb, 0x12, 0xd3, 0x4b, 0x38,
	0xdd, 0x44, 0x49, 0x1b, 0x2c, 0x21, 0xa3, 0xa0, 0x50, 0x4b, 0x81, 0x4e, 0xdd, 0x35, 0x7c, 0xbb,
	0x7b, 0x67, 0x73, 0x75, 0x20, 0xa3, 0xd1, 0x2a, 0x40, 0x4d, 0xb1, 0xb6, 0xc8, 0x11, 0xc0, 0x4c,
	0xaa, 0x20, 0x47, 0x21, 0x19, 0x77, 0x76, 0x5d, 0xc3, 0x37, 0xa9, 0x35, 0x93, 0x8a, 0x6a, 0xe0,
	0x0d, 0x01, 0x06, 0x32, 0x7a, 0x8f, 0x45, 0xc1, 0x22, 0x24, 0x4f, 0xa1, 0x2e, 0x70, 0x81, 0x42,
	0x6b, 0xdd, 0xbf, 0x5d, 0x78, 0xb0, 0x0a, 0xd0, 0x32, 0x4e, 0x1c, 0x68, 0x24, 0x65, 0xce, 0x5a,
	0x74, 0xe5, 0x7a, 0xa7, 0xd0, 0xbc, 0x60, 0xb1, 0x40, 0x4e, 0xe7, 0xe9, 0x48, 0x61, 0x46, 0x5a,
	0x50, 0x0b, 0x93, 0x6a, 0x7b, 0x2b, 0x93, 0x3c, 0x04, 0x0b, 0xbf, 0xc5, 0x2a, 0x08, 0x25, 0x2f,
	0xd3, 0xeb, 0xd4, 0x5c, 0x81, 0x9e, 0xe4, 0xe8, 0x7d, 0x37, 0xe0, 0xde, 0x6f, 0x7f, 0x48, 0x26,
	0x96, 0xe4, 0x15, 0xd8, 0x2b, 0xe1, 0x55, 0x5b, 0x43, 0x4b, 0xbf, 0x7b, 0x73, 0xc2, 0xb5, 0x0a,
	0x0a, 0xe2, 0x5a, 0xd1, 0x29, 0x1c, 0x4c, 0xf5, 0x38, 0x41, 0x3e, 0x4f, 0x83, 0x42, 0x61, 0xa6,
	0x3b, 0xda, 0xdd, 0xc3, 0x4d, 0xe6, 0xad, 0x71, 0x69, 0x73, 0x7a, 0xd3, 0xf5, 0xae, 0xc0, 0xac,
	0x96, 0x4a, 0x1e, 0xc3, 0x7e, 0x28, 0x85, 0xcc, 0x8b, 0x00, 0x53, 0x36, 0x11, 0x58, 0x8a, 0x32,
	0x69, 0xb3, 0xa4, 0xfd, 0x12, 0x5e, 0x2f, 0x71, 0xfb, 0xdf, 0x4b, 0x7c, 0xf6, 0x5c, 0xd7, 0xd6,
	0x88, 0x98, 0xb0, 0x73, 0xf9, 0xe1, 0x62, 0xd8, 0xda, 0x22, 0x36, 0x34, 0x3e, 0xf5, 0xe9, 0xd9,
	0x70, 0xd4, 0x6f, 0x19, 0xc4, 0x82, 0xfa, 0x79, 0xff, 0x6c, 0xfc, 0xae, 0xb5, 0xdd, 0xfd, 0x0c,
	0x8d, 0x51, 0x59, 0x88, 0x8c, 0xe1, 0xe0, 0x97, 0x15, 0x91, 0xe3, 0x4d, 0x97, 0x3f, 0x7f, 0xcd,
	0x0f, 0x8e, 0xfe, 0x7e, 0x21, 0x13, 0x4b, 0x6f, 0xeb, 0x85, 0x71, 0x76, 0x72, 0xf5, 0xfa, 0xbf,
	0x5e, 0x9b, 0x7e, 0x65, 0x6f, 0xf4, 0xef, 0x64, 0x57, 0x1f, 0x2f, 0x7f, 0x06, 0x00, 0x00, 0xff,
	0xff, 0xe6, 0x2d, 0x44, 0x48, 0xb0, 0x03, 0x00, 0x00,
}
