include('../Tiltfile')

repo = 'gcr.io/windmill-test-containers'
docker_build(repo + '/imagetags-common', 'common')
docker_build(repo + '/imagetags-common:stretch', 'common-stretch')
docker_build(repo + '/imagetags-app', 'app')
docker_build(repo + '/imagetags-app:stretch', 'app-stretch')

k8s_yaml(['app.yaml', 'app-stretch.yaml'])
k8s_resource('imagetags', new_name='regular', port_forwards='31000:8000')
k8s_resource('imagetags-stretch', new_name='stretch', port_forwards='31001:8000')
