# -*- mode: Python -*-

include('../Tiltfile')

k8s_yaml('deployment.yaml')
repo = local_git_repo('../../')
docker_build('gcr.io/windmill-test-containers/integration/live_update_after_crash_rebuild',
             '.',
             dockerfile='Dockerfile',
             live_update=[
               sync('.', '/src'),
               run('/src/compile.sh'),
               run('/src/restart.sh'),
             ])

k8s_resource("live-update-after-crash-rebuild", port_forwards=["31234:8000"])
