
enable_feature('custom_deploy')

custom_deploy(
    'custom-deploy-int-test',
    cmd='kubectl apply -o yaml -f ${DEPLOY_FILE}',
    deps=['deploy.yaml', 'foo', 'web/'],
    image_selector='nginx',
    env={'DEPLOY_FILE': 'deploy.yaml'},
    live_update=[
        sync('./web/', '/usr/share/nginx/html/')
    ]
)
k8s_resource(
    'custom-deploy-int-test',
    port_forwards=['54871:80']
)
