FROM golang:1.11-alpine
WORKDIR /go/src/github.com/windmilleng/integration/live_update_two_images_one_manifest/sparkle
ADD sparkle .
ADD start.sh .
ADD restart.sh .
RUN go install github.com/windmilleng/integration/live_update_two_images_one_manifest/sparkle
ENTRYPOINT ./start.sh /go/bin/sparkle
