FROM golang:1.11-alpine
WORKDIR /go/src/github.com/windmilleng/integration/live_update_two_images_one_manifest/tada
ADD tada .
ADD start.sh .
ADD restart.sh .
RUN go install github.com/windmilleng/integration/live_update_two_images_one_manifest/tada
ENTRYPOINT ./start.sh /go/bin/tada
