# -*- mode: Python -*-

docker_compose('docker-compose.yaml')
img = fast_build('gcr.io/windmill-test-containers/dcfastbuild',
                 'Dockerfile',
                 entrypoint='/go/bin/dcfastbuild')
img.add('.', '/go/src/github.com/windmilleng/tilt/integration/dcfastbuild')
img.run('go install github.com/windmilleng/tilt/integration/dcfastbuild/cmd/dcfastbuild')
