apiVersion: apps/v1
kind: Deployment
metadata:
  name: sameimg
  namespace: tilt-integration
  labels:
    app: sameimg
spec:
  selector:
    matchLabels:
      app: sameimg
  template:
    metadata:
      labels:
        app: sameimg
    spec:
      containers:
      - name: c1
        image: sameimg
        command: ["/src/start.sh", "/src/main.sh"]
        args: ["8000"]
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "10m"
      - name: c2
        image: sameimg
        command: ["/src/start.sh", "/src/main.sh"]
        args: ["8001"]
        ports:
          - containerPort: 8001
        resources:
          requests:
            cpu: "10m"
