load('../Tiltfile', 'docker_build_with_restart')

k8s_yaml('job.yaml')
docker_build_with_restart('failing_job', '.', '/fail.sh',
                          live_update=[sync('./fail.sh', '/fail.sh')])
