# -*- mode: Python -*-

k8s_yaml('deployment.yaml')
image_name = 'gcr.io/windmill-test-containers/integration/onewatch'
repo = local_git_repo('../../')
path = repo.path('integration/onewatch')
fast_build(image_name, 'Dockerfile', '/go/bin/onewatch') \
  .add(path, '/go/src/github.com/windmilleng/tilt/integration/onewatch') \
  .run('go install github.com/windmilleng/tilt/integration/onewatch')
