// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/webview/log.proto

package webview

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogSegment struct {
	SpanId               string               `protobuf:"bytes,1,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Text                 string               `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LogSegment) Reset()         { *m = LogSegment{} }
func (m *LogSegment) String() string { return proto.CompactTextString(m) }
func (*LogSegment) ProtoMessage()    {}
func (*LogSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_3da405ef8c289d22, []int{0}
}

func (m *LogSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogSegment.Unmarshal(m, b)
}
func (m *LogSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogSegment.Marshal(b, m, deterministic)
}
func (m *LogSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogSegment.Merge(m, src)
}
func (m *LogSegment) XXX_Size() int {
	return xxx_messageInfo_LogSegment.Size(m)
}
func (m *LogSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_LogSegment.DiscardUnknown(m)
}

var xxx_messageInfo_LogSegment proto.InternalMessageInfo

func (m *LogSegment) GetSpanId() string {
	if m != nil {
		return m.SpanId
	}
	return ""
}

func (m *LogSegment) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *LogSegment) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type LogSpan struct {
	ManifestName         string   `protobuf:"bytes,1,opt,name=manifest_name,json=manifestName,proto3" json:"manifest_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogSpan) Reset()         { *m = LogSpan{} }
func (m *LogSpan) String() string { return proto.CompactTextString(m) }
func (*LogSpan) ProtoMessage()    {}
func (*LogSpan) Descriptor() ([]byte, []int) {
	return fileDescriptor_3da405ef8c289d22, []int{1}
}

func (m *LogSpan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogSpan.Unmarshal(m, b)
}
func (m *LogSpan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogSpan.Marshal(b, m, deterministic)
}
func (m *LogSpan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogSpan.Merge(m, src)
}
func (m *LogSpan) XXX_Size() int {
	return xxx_messageInfo_LogSpan.Size(m)
}
func (m *LogSpan) XXX_DiscardUnknown() {
	xxx_messageInfo_LogSpan.DiscardUnknown(m)
}

var xxx_messageInfo_LogSpan proto.InternalMessageInfo

func (m *LogSpan) GetManifestName() string {
	if m != nil {
		return m.ManifestName
	}
	return ""
}

type LogList struct {
	Spans                map[string]*LogSpan `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Segments             []*LogSegment       `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LogList) Reset()         { *m = LogList{} }
func (m *LogList) String() string { return proto.CompactTextString(m) }
func (*LogList) ProtoMessage()    {}
func (*LogList) Descriptor() ([]byte, []int) {
	return fileDescriptor_3da405ef8c289d22, []int{2}
}

func (m *LogList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogList.Unmarshal(m, b)
}
func (m *LogList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogList.Marshal(b, m, deterministic)
}
func (m *LogList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogList.Merge(m, src)
}
func (m *LogList) XXX_Size() int {
	return xxx_messageInfo_LogList.Size(m)
}
func (m *LogList) XXX_DiscardUnknown() {
	xxx_messageInfo_LogList.DiscardUnknown(m)
}

var xxx_messageInfo_LogList proto.InternalMessageInfo

func (m *LogList) GetSpans() map[string]*LogSpan {
	if m != nil {
		return m.Spans
	}
	return nil
}

func (m *LogList) GetSegments() []*LogSegment {
	if m != nil {
		return m.Segments
	}
	return nil
}

func init() {
	proto.RegisterType((*LogSegment)(nil), "webview.LogSegment")
	proto.RegisterType((*LogSpan)(nil), "webview.LogSpan")
	proto.RegisterType((*LogList)(nil), "webview.LogList")
	proto.RegisterMapType((map[string]*LogSpan)(nil), "webview.LogList.SpansEntry")
}

func init() { proto.RegisterFile("pkg/webview/log.proto", fileDescriptor_3da405ef8c289d22) }

var fileDescriptor_3da405ef8c289d22 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x3f, 0x4f, 0xf3, 0x30,
	0x10, 0xc6, 0x95, 0xfe, 0x7d, 0xdf, 0x2b, 0x48, 0x95, 0x11, 0x22, 0x2a, 0x03, 0x55, 0x91, 0xa0,
	0x2c, 0xb6, 0x28, 0x0b, 0x62, 0x44, 0x62, 0x00, 0x55, 0x0c, 0x81, 0x89, 0xa5, 0x72, 0xe8, 0xd5,
	0x58, 0x8d, 0xed, 0xa8, 0xbe, 0xb6, 0xf4, 0xa3, 0xf1, 0xed, 0x50, 0x9c, 0x04, 0xca, 0x76, 0xb9,
	0x3c, 0xcf, 0xef, 0xee, 0x39, 0xc3, 0x71, 0xbe, 0x54, 0x62, 0x8b, 0xe9, 0x46, 0xe3, 0x56, 0x64,
	0x4e, 0xf1, 0x7c, 0xe5, 0xc8, 0xb1, 0x6e, 0xd5, 0x1a, 0x9c, 0x29, 0xe7, 0x54, 0x86, 0x22, 0xb4,
	0xd3, 0xf5, 0x42, 0x90, 0x36, 0xe8, 0x49, 0x9a, 0xbc, 0x54, 0x8e, 0x34, 0xc0, 0xd4, 0xa9, 0x17,
	0x54, 0x06, 0x2d, 0xb1, 0x13, 0xe8, 0xfa, 0x5c, 0xda, 0x99, 0x9e, 0xc7, 0xd1, 0x30, 0x1a, 0xff,
	0x4f, 0x3a, 0xc5, 0xe7, 0xe3, 0x9c, 0x71, 0x68, 0x15, 0xce, 0xb8, 0x31, 0x8c, 0xc6, 0xbd, 0xc9,
	0x80, 0x97, 0x58, 0x5e, 0x63, 0xf9, 0x6b, 0x8d, 0x4d, 0x82, 0x8e, 0x31, 0x68, 0x11, 0x7e, 0x52,
	0xdc, 0x0c, 0x94, 0x50, 0x8f, 0x38, 0x74, 0x8b, 0x51, 0xb9, 0xb4, 0xec, 0x1c, 0x0e, 0x8d, 0xb4,
	0x7a, 0x81, 0x9e, 0x66, 0x56, 0x1a, 0xac, 0xa6, 0x1d, 0xd4, 0xcd, 0x67, 0x69, 0x70, 0xf4, 0x15,
	0x05, 0xc3, 0x54, 0x7b, 0x62, 0xd7, 0xd0, 0x2e, 0x36, 0xf1, 0x71, 0x34, 0x6c, 0x8e, 0x7b, 0x93,
	0x53, 0x5e, 0x05, 0xe4, 0x95, 0x80, 0x17, 0x58, 0xff, 0x60, 0x69, 0xb5, 0x4b, 0x4a, 0x25, 0x13,
	0xf0, 0xcf, 0x97, 0xb1, 0x7c, 0xdc, 0x08, 0xae, 0xa3, 0x7d, 0x57, 0x15, 0x39, 0xf9, 0x11, 0x0d,
	0x9e, 0x00, 0x7e, 0x29, 0xac, 0x0f, 0xcd, 0x25, 0xee, 0xaa, 0xc5, 0x8a, 0x92, 0x5d, 0x40, 0x7b,
	0x23, 0xb3, 0x75, 0x7d, 0x84, 0xfe, 0x1f, 0x5a, 0x2e, 0x6d, 0x52, 0xfe, 0xbe, 0x6b, 0xdc, 0x46,
	0xf7, 0x57, 0x6f, 0x97, 0x4a, 0xd3, 0xc7, 0x3a, 0xe5, 0xef, 0xce, 0x88, 0xad, 0xb6, 0x73, 0xa3,
	0xb3, 0x0c, 0xad, 0x12, 0xa4, 0x33, 0x12, 0x7b, 0xaf, 0x96, 0x76, 0xc2, 0x11, 0x6f, 0xbe, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x91, 0x21, 0x96, 0x99, 0xcb, 0x01, 0x00, 0x00,
}
