// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/webview/view.proto

package webview

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuildRecord struct {
	Edits                []string             `protobuf:"bytes,1,rep,name=edits,proto3" json:"edits,omitempty"`
	Error                string               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Warnings             []string             `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	FinishTime           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	Log                  string               `protobuf:"bytes,6,opt,name=log,proto3" json:"log,omitempty"`
	IsCrashRebuild       bool                 `protobuf:"varint,7,opt,name=is_crash_rebuild,json=isCrashRebuild,proto3" json:"is_crash_rebuild,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BuildRecord) Reset()         { *m = BuildRecord{} }
func (m *BuildRecord) String() string { return proto.CompactTextString(m) }
func (*BuildRecord) ProtoMessage()    {}
func (*BuildRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{0}
}

func (m *BuildRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRecord.Unmarshal(m, b)
}
func (m *BuildRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRecord.Marshal(b, m, deterministic)
}
func (m *BuildRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRecord.Merge(m, src)
}
func (m *BuildRecord) XXX_Size() int {
	return xxx_messageInfo_BuildRecord.Size(m)
}
func (m *BuildRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRecord.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRecord proto.InternalMessageInfo

func (m *BuildRecord) GetEdits() []string {
	if m != nil {
		return m.Edits
	}
	return nil
}

func (m *BuildRecord) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *BuildRecord) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

func (m *BuildRecord) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *BuildRecord) GetFinishTime() *timestamp.Timestamp {
	if m != nil {
		return m.FinishTime
	}
	return nil
}

func (m *BuildRecord) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *BuildRecord) GetIsCrashRebuild() bool {
	if m != nil {
		return m.IsCrashRebuild
	}
	return false
}

type K8SResourceInfo struct {
	PodName              string   `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodCreationTime      string   `protobuf:"bytes,2,opt,name=pod_creation_time,json=podCreationTime,proto3" json:"pod_creation_time,omitempty"`
	PodUpdateStartTime   string   `protobuf:"bytes,3,opt,name=pod_update_start_time,json=podUpdateStartTime,proto3" json:"pod_update_start_time,omitempty"`
	PodStatus            string   `protobuf:"bytes,4,opt,name=pod_status,json=podStatus,proto3" json:"pod_status,omitempty"`
	PodStatusMessage     string   `protobuf:"bytes,5,opt,name=pod_status_message,json=podStatusMessage,proto3" json:"pod_status_message,omitempty"`
	AllContainersReady   bool     `protobuf:"varint,6,opt,name=all_containers_ready,json=allContainersReady,proto3" json:"all_containers_ready,omitempty"`
	PodRestarts          int32    `protobuf:"varint,7,opt,name=pod_restarts,json=podRestarts,proto3" json:"pod_restarts,omitempty"`
	PodLog               string   `protobuf:"bytes,8,opt,name=pod_log,json=podLog,proto3" json:"pod_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *K8SResourceInfo) Reset()         { *m = K8SResourceInfo{} }
func (m *K8SResourceInfo) String() string { return proto.CompactTextString(m) }
func (*K8SResourceInfo) ProtoMessage()    {}
func (*K8SResourceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{1}
}

func (m *K8SResourceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_K8SResourceInfo.Unmarshal(m, b)
}
func (m *K8SResourceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_K8SResourceInfo.Marshal(b, m, deterministic)
}
func (m *K8SResourceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_K8SResourceInfo.Merge(m, src)
}
func (m *K8SResourceInfo) XXX_Size() int {
	return xxx_messageInfo_K8SResourceInfo.Size(m)
}
func (m *K8SResourceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_K8SResourceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_K8SResourceInfo proto.InternalMessageInfo

func (m *K8SResourceInfo) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *K8SResourceInfo) GetPodCreationTime() string {
	if m != nil {
		return m.PodCreationTime
	}
	return ""
}

func (m *K8SResourceInfo) GetPodUpdateStartTime() string {
	if m != nil {
		return m.PodUpdateStartTime
	}
	return ""
}

func (m *K8SResourceInfo) GetPodStatus() string {
	if m != nil {
		return m.PodStatus
	}
	return ""
}

func (m *K8SResourceInfo) GetPodStatusMessage() string {
	if m != nil {
		return m.PodStatusMessage
	}
	return ""
}

func (m *K8SResourceInfo) GetAllContainersReady() bool {
	if m != nil {
		return m.AllContainersReady
	}
	return false
}

func (m *K8SResourceInfo) GetPodRestarts() int32 {
	if m != nil {
		return m.PodRestarts
	}
	return 0
}

func (m *K8SResourceInfo) GetPodLog() string {
	if m != nil {
		return m.PodLog
	}
	return ""
}

type DCResourceInfo struct {
	ConfigPaths          []string             `protobuf:"bytes,1,rep,name=config_paths,json=configPaths,proto3" json:"config_paths,omitempty"`
	ContainerStatus      string               `protobuf:"bytes,2,opt,name=container_status,json=containerStatus,proto3" json:"container_status,omitempty"`
	ContainerID          string               `protobuf:"bytes,3,opt,name=containerID,proto3" json:"containerID,omitempty"`
	Log                  string               `protobuf:"bytes,4,opt,name=log,proto3" json:"log,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DCResourceInfo) Reset()         { *m = DCResourceInfo{} }
func (m *DCResourceInfo) String() string { return proto.CompactTextString(m) }
func (*DCResourceInfo) ProtoMessage()    {}
func (*DCResourceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{2}
}

func (m *DCResourceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DCResourceInfo.Unmarshal(m, b)
}
func (m *DCResourceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DCResourceInfo.Marshal(b, m, deterministic)
}
func (m *DCResourceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCResourceInfo.Merge(m, src)
}
func (m *DCResourceInfo) XXX_Size() int {
	return xxx_messageInfo_DCResourceInfo.Size(m)
}
func (m *DCResourceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DCResourceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DCResourceInfo proto.InternalMessageInfo

func (m *DCResourceInfo) GetConfigPaths() []string {
	if m != nil {
		return m.ConfigPaths
	}
	return nil
}

func (m *DCResourceInfo) GetContainerStatus() string {
	if m != nil {
		return m.ContainerStatus
	}
	return ""
}

func (m *DCResourceInfo) GetContainerID() string {
	if m != nil {
		return m.ContainerID
	}
	return ""
}

func (m *DCResourceInfo) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *DCResourceInfo) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

type YAMLResourceInfo struct {
	K8SResources         []string `protobuf:"bytes,1,rep,name=k8s_resources,json=k8sResources,proto3" json:"k8s_resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YAMLResourceInfo) Reset()         { *m = YAMLResourceInfo{} }
func (m *YAMLResourceInfo) String() string { return proto.CompactTextString(m) }
func (*YAMLResourceInfo) ProtoMessage()    {}
func (*YAMLResourceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{3}
}

func (m *YAMLResourceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YAMLResourceInfo.Unmarshal(m, b)
}
func (m *YAMLResourceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YAMLResourceInfo.Marshal(b, m, deterministic)
}
func (m *YAMLResourceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YAMLResourceInfo.Merge(m, src)
}
func (m *YAMLResourceInfo) XXX_Size() int {
	return xxx_messageInfo_YAMLResourceInfo.Size(m)
}
func (m *YAMLResourceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_YAMLResourceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_YAMLResourceInfo proto.InternalMessageInfo

func (m *YAMLResourceInfo) GetK8SResources() []string {
	if m != nil {
		return m.K8SResources
	}
	return nil
}

type LocalResourceInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalResourceInfo) Reset()         { *m = LocalResourceInfo{} }
func (m *LocalResourceInfo) String() string { return proto.CompactTextString(m) }
func (*LocalResourceInfo) ProtoMessage()    {}
func (*LocalResourceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{4}
}

func (m *LocalResourceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalResourceInfo.Unmarshal(m, b)
}
func (m *LocalResourceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalResourceInfo.Marshal(b, m, deterministic)
}
func (m *LocalResourceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalResourceInfo.Merge(m, src)
}
func (m *LocalResourceInfo) XXX_Size() int {
	return xxx_messageInfo_LocalResourceInfo.Size(m)
}
func (m *LocalResourceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalResourceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LocalResourceInfo proto.InternalMessageInfo

type Alert struct {
	AlertType string `protobuf:"bytes,1,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"`
	Header    string `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// TODO(dmiller): this should be a timestamp, but sometimes incorrectly formatted times get set here
	// like when there's a Pod that has PodStatusError.
	// We should figure out how those times are being set, and fix them to parse as protobuf.Timestamp
	// correctly
	Timestamp            string   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ResourceName         string   `protobuf:"bytes,5,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Alert) Reset()         { *m = Alert{} }
func (m *Alert) String() string { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()    {}
func (*Alert) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{5}
}

func (m *Alert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alert.Unmarshal(m, b)
}
func (m *Alert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alert.Marshal(b, m, deterministic)
}
func (m *Alert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alert.Merge(m, src)
}
func (m *Alert) XXX_Size() int {
	return xxx_messageInfo_Alert.Size(m)
}
func (m *Alert) XXX_DiscardUnknown() {
	xxx_messageInfo_Alert.DiscardUnknown(m)
}

var xxx_messageInfo_Alert proto.InternalMessageInfo

func (m *Alert) GetAlertType() string {
	if m != nil {
		return m.AlertType
	}
	return ""
}

func (m *Alert) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *Alert) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Alert) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Alert) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

type Facet struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Facet) Reset()         { *m = Facet{} }
func (m *Facet) String() string { return proto.CompactTextString(m) }
func (*Facet) ProtoMessage()    {}
func (*Facet) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{6}
}

func (m *Facet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Facet.Unmarshal(m, b)
}
func (m *Facet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Facet.Marshal(b, m, deterministic)
}
func (m *Facet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Facet.Merge(m, src)
}
func (m *Facet) XXX_Size() int {
	return xxx_messageInfo_Facet.Size(m)
}
func (m *Facet) XXX_DiscardUnknown() {
	xxx_messageInfo_Facet.DiscardUnknown(m)
}

var xxx_messageInfo_Facet proto.InternalMessageInfo

func (m *Facet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Facet) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Resource struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DirectoriesWatched   []string             `protobuf:"bytes,2,rep,name=directories_watched,json=directoriesWatched,proto3" json:"directories_watched,omitempty"`
	PathsWatched         []string             `protobuf:"bytes,3,rep,name=paths_watched,json=pathsWatched,proto3" json:"paths_watched,omitempty"`
	LastDeployTime       *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_deploy_time,json=lastDeployTime,proto3" json:"last_deploy_time,omitempty"`
	TriggerMode          int32                `protobuf:"varint,5,opt,name=trigger_mode,json=triggerMode,proto3" json:"trigger_mode,omitempty"`
	BuildHistory         []*BuildRecord       `protobuf:"bytes,6,rep,name=build_history,json=buildHistory,proto3" json:"build_history,omitempty"`
	CurrentBuild         *BuildRecord         `protobuf:"bytes,7,opt,name=current_build,json=currentBuild,proto3" json:"current_build,omitempty"`
	PendingBuildReason   int32                `protobuf:"varint,8,opt,name=pending_build_reason,json=pendingBuildReason,proto3" json:"pending_build_reason,omitempty"`
	PendingBuildEdits    []string             `protobuf:"bytes,9,rep,name=pending_build_edits,json=pendingBuildEdits,proto3" json:"pending_build_edits,omitempty"`
	PendingBuildSince    *timestamp.Timestamp `protobuf:"bytes,10,opt,name=pending_build_since,json=pendingBuildSince,proto3" json:"pending_build_since,omitempty"`
	HasPendingChanges    bool                 `protobuf:"varint,11,opt,name=has_pending_changes,json=hasPendingChanges,proto3" json:"has_pending_changes,omitempty"`
	Endpoints            []string             `protobuf:"bytes,12,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	PodID                string               `protobuf:"bytes,13,opt,name=podID,proto3" json:"podID,omitempty"`
	K8SResourceInfo      *K8SResourceInfo     `protobuf:"bytes,14,opt,name=k8s_resource_info,json=k8sResourceInfo,proto3" json:"k8s_resource_info,omitempty"`
	DcResourceInfo       *DCResourceInfo      `protobuf:"bytes,15,opt,name=dc_resource_info,json=dcResourceInfo,proto3" json:"dc_resource_info,omitempty"`
	YamlResourceInfo     *YAMLResourceInfo    `protobuf:"bytes,16,opt,name=yaml_resource_info,json=yamlResourceInfo,proto3" json:"yaml_resource_info,omitempty"`
	LocalResourceInfo    *LocalResourceInfo   `protobuf:"bytes,17,opt,name=local_resource_info,json=localResourceInfo,proto3" json:"local_resource_info,omitempty"`
	RuntimeStatus        string               `protobuf:"bytes,18,opt,name=runtime_status,json=runtimeStatus,proto3" json:"runtime_status,omitempty"`
	IsTiltfile           bool                 `protobuf:"varint,19,opt,name=is_tiltfile,json=isTiltfile,proto3" json:"is_tiltfile,omitempty"`
	ShowBuildStatus      bool                 `protobuf:"varint,20,opt,name=show_build_status,json=showBuildStatus,proto3" json:"show_build_status,omitempty"`
	CombinedLog          string               `protobuf:"bytes,21,opt,name=combined_log,json=combinedLog,proto3" json:"combined_log,omitempty"`
	CrashLog             string               `protobuf:"bytes,22,opt,name=crash_log,json=crashLog,proto3" json:"crash_log,omitempty"`
	Alerts               []*Alert             `protobuf:"bytes,23,rep,name=alerts,proto3" json:"alerts,omitempty"`
	Facets               []*Facet             `protobuf:"bytes,24,rep,name=facets,proto3" json:"facets,omitempty"`
	Queued               bool                 `protobuf:"varint,25,opt,name=queued,proto3" json:"queued,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{7}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetDirectoriesWatched() []string {
	if m != nil {
		return m.DirectoriesWatched
	}
	return nil
}

func (m *Resource) GetPathsWatched() []string {
	if m != nil {
		return m.PathsWatched
	}
	return nil
}

func (m *Resource) GetLastDeployTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastDeployTime
	}
	return nil
}

func (m *Resource) GetTriggerMode() int32 {
	if m != nil {
		return m.TriggerMode
	}
	return 0
}

func (m *Resource) GetBuildHistory() []*BuildRecord {
	if m != nil {
		return m.BuildHistory
	}
	return nil
}

func (m *Resource) GetCurrentBuild() *BuildRecord {
	if m != nil {
		return m.CurrentBuild
	}
	return nil
}

func (m *Resource) GetPendingBuildReason() int32 {
	if m != nil {
		return m.PendingBuildReason
	}
	return 0
}

func (m *Resource) GetPendingBuildEdits() []string {
	if m != nil {
		return m.PendingBuildEdits
	}
	return nil
}

func (m *Resource) GetPendingBuildSince() *timestamp.Timestamp {
	if m != nil {
		return m.PendingBuildSince
	}
	return nil
}

func (m *Resource) GetHasPendingChanges() bool {
	if m != nil {
		return m.HasPendingChanges
	}
	return false
}

func (m *Resource) GetEndpoints() []string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *Resource) GetPodID() string {
	if m != nil {
		return m.PodID
	}
	return ""
}

func (m *Resource) GetK8SResourceInfo() *K8SResourceInfo {
	if m != nil {
		return m.K8SResourceInfo
	}
	return nil
}

func (m *Resource) GetDcResourceInfo() *DCResourceInfo {
	if m != nil {
		return m.DcResourceInfo
	}
	return nil
}

func (m *Resource) GetYamlResourceInfo() *YAMLResourceInfo {
	if m != nil {
		return m.YamlResourceInfo
	}
	return nil
}

func (m *Resource) GetLocalResourceInfo() *LocalResourceInfo {
	if m != nil {
		return m.LocalResourceInfo
	}
	return nil
}

func (m *Resource) GetRuntimeStatus() string {
	if m != nil {
		return m.RuntimeStatus
	}
	return ""
}

func (m *Resource) GetIsTiltfile() bool {
	if m != nil {
		return m.IsTiltfile
	}
	return false
}

func (m *Resource) GetShowBuildStatus() bool {
	if m != nil {
		return m.ShowBuildStatus
	}
	return false
}

func (m *Resource) GetCombinedLog() string {
	if m != nil {
		return m.CombinedLog
	}
	return ""
}

func (m *Resource) GetCrashLog() string {
	if m != nil {
		return m.CrashLog
	}
	return ""
}

func (m *Resource) GetAlerts() []*Alert {
	if m != nil {
		return m.Alerts
	}
	return nil
}

func (m *Resource) GetFacets() []*Facet {
	if m != nil {
		return m.Facets
	}
	return nil
}

func (m *Resource) GetQueued() bool {
	if m != nil {
		return m.Queued
	}
	return false
}

type TiltBuild struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	CommitSHA            string   `protobuf:"bytes,2,opt,name=commitSHA,proto3" json:"commitSHA,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Dev                  bool     `protobuf:"varint,4,opt,name=dev,proto3" json:"dev,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TiltBuild) Reset()         { *m = TiltBuild{} }
func (m *TiltBuild) String() string { return proto.CompactTextString(m) }
func (*TiltBuild) ProtoMessage()    {}
func (*TiltBuild) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{8}
}

func (m *TiltBuild) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TiltBuild.Unmarshal(m, b)
}
func (m *TiltBuild) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TiltBuild.Marshal(b, m, deterministic)
}
func (m *TiltBuild) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TiltBuild.Merge(m, src)
}
func (m *TiltBuild) XXX_Size() int {
	return xxx_messageInfo_TiltBuild.Size(m)
}
func (m *TiltBuild) XXX_DiscardUnknown() {
	xxx_messageInfo_TiltBuild.DiscardUnknown(m)
}

var xxx_messageInfo_TiltBuild proto.InternalMessageInfo

func (m *TiltBuild) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *TiltBuild) GetCommitSHA() string {
	if m != nil {
		return m.CommitSHA
	}
	return ""
}

func (m *TiltBuild) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *TiltBuild) GetDev() bool {
	if m != nil {
		return m.Dev
	}
	return false
}

type VersionSettings struct {
	CheckUpdates         bool     `protobuf:"varint,1,opt,name=check_updates,json=checkUpdates,proto3" json:"check_updates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionSettings) Reset()         { *m = VersionSettings{} }
func (m *VersionSettings) String() string { return proto.CompactTextString(m) }
func (*VersionSettings) ProtoMessage()    {}
func (*VersionSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{9}
}

func (m *VersionSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionSettings.Unmarshal(m, b)
}
func (m *VersionSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionSettings.Marshal(b, m, deterministic)
}
func (m *VersionSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionSettings.Merge(m, src)
}
func (m *VersionSettings) XXX_Size() int {
	return xxx_messageInfo_VersionSettings.Size(m)
}
func (m *VersionSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionSettings.DiscardUnknown(m)
}

var xxx_messageInfo_VersionSettings proto.InternalMessageInfo

func (m *VersionSettings) GetCheckUpdates() bool {
	if m != nil {
		return m.CheckUpdates
	}
	return false
}

type View struct {
	Log       string      `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	Resources []*Resource `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	// We used to have a field that allowed users to dynamically
	// prepend timestamps in logs.
	DEPRECATEDLogTimestamps bool             `protobuf:"varint,3,opt,name=DEPRECATED_log_timestamps,json=DEPRECATEDLogTimestamps,proto3" json:"DEPRECATED_log_timestamps,omitempty"`
	FeatureFlags            map[string]bool  `protobuf:"bytes,4,rep,name=feature_flags,json=featureFlags,proto3" json:"feature_flags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	NeedsAnalyticsNudge     bool             `protobuf:"varint,5,opt,name=needs_analytics_nudge,json=needsAnalyticsNudge,proto3" json:"needs_analytics_nudge,omitempty"`
	RunningTiltBuild        *TiltBuild       `protobuf:"bytes,6,opt,name=running_tilt_build,json=runningTiltBuild,proto3" json:"running_tilt_build,omitempty"`
	LatestTiltBuild         *TiltBuild       `protobuf:"bytes,7,opt,name=latest_tilt_build,json=latestTiltBuild,proto3" json:"latest_tilt_build,omitempty"`
	VersionSettings         *VersionSettings `protobuf:"bytes,12,opt,name=version_settings,json=versionSettings,proto3" json:"version_settings,omitempty"`
	TiltCloudUsername       string           `protobuf:"bytes,8,opt,name=tilt_cloud_username,json=tiltCloudUsername,proto3" json:"tilt_cloud_username,omitempty"`
	TiltCloudSchemeHost     string           `protobuf:"bytes,9,opt,name=tilt_cloud_schemeHost,json=tiltCloudSchemeHost,proto3" json:"tilt_cloud_schemeHost,omitempty"`
	TiltCloudTeamID         string           `protobuf:"bytes,10,opt,name=tilt_cloud_teamID,json=tiltCloudTeamID,proto3" json:"tilt_cloud_teamID,omitempty"`
	FatalError              string           `protobuf:"bytes,11,opt,name=fatal_error,json=fatalError,proto3" json:"fatal_error,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}         `json:"-"`
	XXX_unrecognized        []byte           `json:"-"`
	XXX_sizecache           int32            `json:"-"`
}

func (m *View) Reset()         { *m = View{} }
func (m *View) String() string { return proto.CompactTextString(m) }
func (*View) ProtoMessage()    {}
func (*View) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{10}
}

func (m *View) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_View.Unmarshal(m, b)
}
func (m *View) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_View.Marshal(b, m, deterministic)
}
func (m *View) XXX_Merge(src proto.Message) {
	xxx_messageInfo_View.Merge(m, src)
}
func (m *View) XXX_Size() int {
	return xxx_messageInfo_View.Size(m)
}
func (m *View) XXX_DiscardUnknown() {
	xxx_messageInfo_View.DiscardUnknown(m)
}

var xxx_messageInfo_View proto.InternalMessageInfo

func (m *View) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *View) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *View) GetDEPRECATEDLogTimestamps() bool {
	if m != nil {
		return m.DEPRECATEDLogTimestamps
	}
	return false
}

func (m *View) GetFeatureFlags() map[string]bool {
	if m != nil {
		return m.FeatureFlags
	}
	return nil
}

func (m *View) GetNeedsAnalyticsNudge() bool {
	if m != nil {
		return m.NeedsAnalyticsNudge
	}
	return false
}

func (m *View) GetRunningTiltBuild() *TiltBuild {
	if m != nil {
		return m.RunningTiltBuild
	}
	return nil
}

func (m *View) GetLatestTiltBuild() *TiltBuild {
	if m != nil {
		return m.LatestTiltBuild
	}
	return nil
}

func (m *View) GetVersionSettings() *VersionSettings {
	if m != nil {
		return m.VersionSettings
	}
	return nil
}

func (m *View) GetTiltCloudUsername() string {
	if m != nil {
		return m.TiltCloudUsername
	}
	return ""
}

func (m *View) GetTiltCloudSchemeHost() string {
	if m != nil {
		return m.TiltCloudSchemeHost
	}
	return ""
}

func (m *View) GetTiltCloudTeamID() string {
	if m != nil {
		return m.TiltCloudTeamID
	}
	return ""
}

func (m *View) GetFatalError() string {
	if m != nil {
		return m.FatalError
	}
	return ""
}

type GetViewRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetViewRequest) Reset()         { *m = GetViewRequest{} }
func (m *GetViewRequest) String() string { return proto.CompactTextString(m) }
func (*GetViewRequest) ProtoMessage()    {}
func (*GetViewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{11}
}

func (m *GetViewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetViewRequest.Unmarshal(m, b)
}
func (m *GetViewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetViewRequest.Marshal(b, m, deterministic)
}
func (m *GetViewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetViewRequest.Merge(m, src)
}
func (m *GetViewRequest) XXX_Size() int {
	return xxx_messageInfo_GetViewRequest.Size(m)
}
func (m *GetViewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetViewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetViewRequest proto.InternalMessageInfo

type SnapshotHighlight struct {
	BeginningLogID       string   `protobuf:"bytes,1,opt,name=beginning_logID,json=beginningLogID,proto3" json:"beginning_logID,omitempty"`
	EndingLogID          string   `protobuf:"bytes,2,opt,name=ending_logID,json=endingLogID,proto3" json:"ending_logID,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotHighlight) Reset()         { *m = SnapshotHighlight{} }
func (m *SnapshotHighlight) String() string { return proto.CompactTextString(m) }
func (*SnapshotHighlight) ProtoMessage()    {}
func (*SnapshotHighlight) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{12}
}

func (m *SnapshotHighlight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotHighlight.Unmarshal(m, b)
}
func (m *SnapshotHighlight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotHighlight.Marshal(b, m, deterministic)
}
func (m *SnapshotHighlight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotHighlight.Merge(m, src)
}
func (m *SnapshotHighlight) XXX_Size() int {
	return xxx_messageInfo_SnapshotHighlight.Size(m)
}
func (m *SnapshotHighlight) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotHighlight.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotHighlight proto.InternalMessageInfo

func (m *SnapshotHighlight) GetBeginningLogID() string {
	if m != nil {
		return m.BeginningLogID
	}
	return ""
}

func (m *SnapshotHighlight) GetEndingLogID() string {
	if m != nil {
		return m.EndingLogID
	}
	return ""
}

func (m *SnapshotHighlight) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Snapshot struct {
	View                 *View              `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	IsSidebarClosed      bool               `protobuf:"varint,2,opt,name=is_sidebar_closed,json=isSidebarClosed,proto3" json:"is_sidebar_closed,omitempty"`
	Path                 string             `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	SnapshotHighlight    *SnapshotHighlight `protobuf:"bytes,4,opt,name=snapshot_highlight,json=snapshotHighlight,proto3" json:"snapshot_highlight,omitempty"`
	SnapshotLink         string             `protobuf:"bytes,5,opt,name=snapshot_link,json=snapshotLink,proto3" json:"snapshot_link,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{13}
}

func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetView() *View {
	if m != nil {
		return m.View
	}
	return nil
}

func (m *Snapshot) GetIsSidebarClosed() bool {
	if m != nil {
		return m.IsSidebarClosed
	}
	return false
}

func (m *Snapshot) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Snapshot) GetSnapshotHighlight() *SnapshotHighlight {
	if m != nil {
		return m.SnapshotHighlight
	}
	return nil
}

func (m *Snapshot) GetSnapshotLink() string {
	if m != nil {
		return m.SnapshotLink
	}
	return ""
}

type UploadSnapshotResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadSnapshotResponse) Reset()         { *m = UploadSnapshotResponse{} }
func (m *UploadSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*UploadSnapshotResponse) ProtoMessage()    {}
func (*UploadSnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{14}
}

func (m *UploadSnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadSnapshotResponse.Unmarshal(m, b)
}
func (m *UploadSnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadSnapshotResponse.Marshal(b, m, deterministic)
}
func (m *UploadSnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadSnapshotResponse.Merge(m, src)
}
func (m *UploadSnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_UploadSnapshotResponse.Size(m)
}
func (m *UploadSnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadSnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadSnapshotResponse proto.InternalMessageInfo

func (m *UploadSnapshotResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*BuildRecord)(nil), "webview.BuildRecord")
	proto.RegisterType((*K8SResourceInfo)(nil), "webview.K8sResourceInfo")
	proto.RegisterType((*DCResourceInfo)(nil), "webview.DCResourceInfo")
	proto.RegisterType((*YAMLResourceInfo)(nil), "webview.YAMLResourceInfo")
	proto.RegisterType((*LocalResourceInfo)(nil), "webview.LocalResourceInfo")
	proto.RegisterType((*Alert)(nil), "webview.Alert")
	proto.RegisterType((*Facet)(nil), "webview.Facet")
	proto.RegisterType((*Resource)(nil), "webview.Resource")
	proto.RegisterType((*TiltBuild)(nil), "webview.TiltBuild")
	proto.RegisterType((*VersionSettings)(nil), "webview.VersionSettings")
	proto.RegisterType((*View)(nil), "webview.View")
	proto.RegisterMapType((map[string]bool)(nil), "webview.View.FeatureFlagsEntry")
	proto.RegisterType((*GetViewRequest)(nil), "webview.GetViewRequest")
	proto.RegisterType((*SnapshotHighlight)(nil), "webview.SnapshotHighlight")
	proto.RegisterType((*Snapshot)(nil), "webview.Snapshot")
	proto.RegisterType((*UploadSnapshotResponse)(nil), "webview.UploadSnapshotResponse")
}

func init() { proto.RegisterFile("pkg/webview/view.proto", fileDescriptor_961ad0c6909086c3) }

var fileDescriptor_961ad0c6909086c3 = []byte{
	// 1740 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0x4b, 0x6f, 0x1b, 0xc9,
	0x11, 0x06, 0x65, 0x3d, 0xc8, 0x22, 0xc5, 0x47, 0xcb, 0x96, 0xc7, 0x8a, 0x03, 0xcb, 0x63, 0x24,
	0xab, 0x35, 0x02, 0x31, 0xab, 0x00, 0x89, 0xd7, 0x01, 0x92, 0x68, 0x45, 0xed, 0x5a, 0x1b, 0x79,
	0x61, 0x8c, 0x64, 0x07, 0xc9, 0x65, 0xd0, 0x9a, 0x69, 0x0e, 0x1b, 0x1c, 0x4e, 0xcf, 0x4e, 0xf7,
	0x48, 0xe1, 0x35, 0xb7, 0x9c, 0x73, 0xcc, 0x21, 0x3f, 0x23, 0xf9, 0x05, 0xb9, 0xe5, 0x94, 0x73,
	0x6e, 0xf9, 0x21, 0x41, 0x55, 0x4f, 0x0f, 0x1f, 0xda, 0xc5, 0x66, 0x2f, 0xc4, 0xf4, 0x57, 0x8f,
	0xae, 0xae, 0xae, 0xfa, 0xaa, 0x09, 0xfb, 0xf9, 0x34, 0x19, 0xde, 0x89, 0x9b, 0x5b, 0x29, 0xee,
	0x86, 0xf8, 0x73, 0x9c, 0x17, 0xca, 0x28, 0xb6, 0x53, 0x61, 0x07, 0x4f, 0x13, 0xa5, 0x92, 0x54,
	0x0c, 0x79, 0x2e, 0x87, 0x3c, 0xcb, 0x94, 0xe1, 0x46, 0xaa, 0x4c, 0x5b, 0xb5, 0x83, 0x67, 0x95,
	0x94, 0x56, 0x37, 0xe5, 0x78, 0x68, 0xe4, 0x4c, 0x68, 0xc3, 0x67, 0xb9, 0x55, 0xf0, 0xff, 0xbc,
	0x01, 0xed, 0xcf, 0x4a, 0x99, 0xc6, 0x81, 0x88, 0x54, 0x11, 0xb3, 0x87, 0xb0, 0x25, 0x62, 0x69,
	0xb4, 0xd7, 0x38, 0x7c, 0x70, 0xd4, 0x0a, 0xec, 0x82, 0xd0, 0xa2, 0x50, 0x85, 0xb7, 0x71, 0xd8,
	0x20, 0x14, 0x17, 0xec, 0x00, 0x9a, 0x77, 0xbc, 0xc8, 0x64, 0x96, 0x68, 0xef, 0x01, 0xa9, 0xd7,
	0x6b, 0xf6, 0x29, 0x80, 0x36, 0xbc, 0x30, 0x21, 0x6e, 0xe8, 0x6d, 0x1e, 0x36, 0x8e, 0xda, 0x27,
	0x07, 0xc7, 0x36, 0x9a, 0x63, 0x17, 0xcd, 0xf1, 0xb5, 0x8b, 0x26, 0x68, 0x91, 0x36, 0xae, 0xd9,
	0x2f, 0xa1, 0x3d, 0x96, 0x99, 0xd4, 0x13, 0x6b, 0xbb, 0xf5, 0x9d, 0xb6, 0x60, 0xd5, 0xc9, 0xb8,
	0x0f, 0x0f, 0x52, 0x95, 0x78, 0xdb, 0x14, 0x27, 0x7e, 0xb2, 0x23, 0xe8, 0x4b, 0x1d, 0x46, 0x05,
	0xd7, 0x93, 0xb0, 0x10, 0x37, 0x78, 0x56, 0x6f, 0xe7, 0xb0, 0x71, 0xd4, 0x0c, 0xba, 0x52, 0x9f,
	0x21, 0x1c, 0x58, 0xd4, 0xff, 0xe7, 0x06, 0xf4, 0x7e, 0xfb, 0x4a, 0x07, 0x42, 0xab, 0xb2, 0x88,
	0xc4, 0x45, 0x36, 0x56, 0xec, 0x09, 0x34, 0x73, 0x15, 0x87, 0x19, 0x9f, 0x09, 0xaf, 0x41, 0x4e,
	0x77, 0x72, 0x15, 0x7f, 0xc5, 0x67, 0x82, 0xbd, 0x84, 0x01, 0x8a, 0xa2, 0x42, 0x50, 0xca, 0x6d,
	0xb4, 0x36, 0x41, 0xbd, 0x5c, 0xc5, 0x67, 0x15, 0x4e, 0x61, 0x7d, 0x02, 0x8f, 0x50, 0xb7, 0xcc,
	0x63, 0x6e, 0x44, 0xb8, 0x94, 0x99, 0x07, 0xa4, 0xcf, 0x72, 0x15, 0xbf, 0x27, 0xd9, 0x55, 0x9d,
	0x86, 0x1f, 0x02, 0xa0, 0x89, 0x36, 0xdc, 0x94, 0x9a, 0x32, 0xd8, 0x0a, 0x5a, 0xb9, 0x8a, 0xaf,
	0x08, 0x60, 0x3f, 0x01, 0xb6, 0x10, 0x87, 0x33, 0xa1, 0x35, 0x4f, 0x6c, 0xb2, 0x5a, 0x41, 0xbf,
	0x56, 0x7b, 0x6b, 0x71, 0xf6, 0x53, 0x78, 0xc8, 0xd3, 0x34, 0x8c, 0x54, 0x66, 0xb8, 0xcc, 0x44,
	0xa1, 0xc3, 0x42, 0xf0, 0x78, 0x4e, 0x79, 0x6a, 0x06, 0x8c, 0xa7, 0xe9, 0x59, 0x2d, 0x0a, 0x50,
	0xc2, 0x9e, 0x43, 0x07, 0xfd, 0x17, 0x82, 0x82, 0xd5, 0x94, 0xb2, 0xad, 0xa0, 0x9d, 0xab, 0x38,
	0xa8, 0x20, 0xf6, 0x18, 0x30, 0x17, 0x21, 0xe6, 0xbb, 0x49, 0xfb, 0x6e, 0xe7, 0x2a, 0xbe, 0x54,
	0x89, 0xff, 0xaf, 0x06, 0x74, 0x47, 0x67, 0x2b, 0x79, 0x7c, 0x0e, 0x9d, 0x48, 0x65, 0x63, 0x99,
	0x84, 0x39, 0x37, 0x13, 0x57, 0x5e, 0x6d, 0x8b, 0xbd, 0x43, 0x88, 0x7d, 0x0c, 0xfd, 0x3a, 0x3e,
	0x77, 0xec, 0x2a, 0x9d, 0x35, 0x5e, 0x1d, 0xfe, 0x10, 0xda, 0x35, 0x74, 0x31, 0xaa, 0x92, 0xb8,
	0x0c, 0xb9, 0x3a, 0xd8, 0x5c, 0xd4, 0xc1, 0x6a, 0x45, 0x6e, 0x7d, 0x8f, 0x8a, 0xf4, 0x7f, 0x01,
	0xfd, 0xdf, 0x9f, 0xbe, 0xbd, 0x5c, 0x39, 0xd0, 0x0b, 0xd8, 0x9d, 0xbe, 0xc2, 0x34, 0x5a, 0xcc,
	0x9d, 0xa8, 0x33, 0x5d, 0x14, 0x90, 0xf6, 0xf7, 0x60, 0x70, 0xa9, 0x22, 0x9e, 0x2e, 0x5b, 0xfa,
	0x7f, 0x6d, 0xc0, 0xd6, 0x69, 0x2a, 0x0a, 0x83, 0x57, 0xcc, 0xf1, 0x23, 0x34, 0xf3, 0xdc, 0x95,
	0x57, 0x8b, 0x90, 0xeb, 0x79, 0x2e, 0xd8, 0x3e, 0x6c, 0x4f, 0x04, 0x8f, 0x85, 0x6b, 0xbb, 0x6a,
	0xc5, 0x3c, 0xd8, 0x71, 0xf7, 0x6d, 0x4f, 0xee, 0x96, 0xec, 0x29, 0xb4, 0xea, 0x06, 0x77, 0x25,
	0x53, 0x03, 0x18, 0xb2, 0x0b, 0xd7, 0x16, 0xb4, 0xad, 0x96, 0x8e, 0x03, 0xb1, 0xaa, 0xfd, 0x4f,
	0x60, 0xeb, 0x73, 0x1e, 0x09, 0xc3, 0x18, 0x6c, 0x2e, 0x55, 0x3d, 0x7d, 0x23, 0x0f, 0xdc, 0xf2,
	0xb4, 0x74, 0x65, 0x6e, 0x17, 0xfe, 0xdf, 0x5a, 0xd0, 0x74, 0x27, 0xfc, 0x46, 0xb3, 0x21, 0xec,
	0xc5, 0xb2, 0x10, 0x91, 0x51, 0x85, 0x14, 0x3a, 0xbc, 0xe3, 0x26, 0x9a, 0x88, 0xd8, 0xdb, 0xa0,
	0x8c, 0xb1, 0x25, 0xd1, 0xef, 0xac, 0x04, 0x23, 0xa5, 0x32, 0xa9, 0x55, 0x2d, 0xbd, 0x74, 0x08,
	0x74, 0x4a, 0x23, 0xe8, 0xa7, 0x5c, 0x9b, 0x30, 0x16, 0x79, 0xaa, 0xe6, 0xff, 0x2f, 0xd1, 0x74,
	0xd1, 0x66, 0x44, 0x26, 0xd4, 0x66, 0xcf, 0xa1, 0x63, 0x0a, 0x99, 0x24, 0xa2, 0x08, 0x67, 0x2a,
	0xb6, 0x39, 0xd9, 0x0a, 0xda, 0x15, 0xf6, 0x56, 0xc5, 0x82, 0x7d, 0x0a, 0xbb, 0x44, 0x10, 0xe1,
	0x44, 0x6a, 0xa3, 0x0a, 0xec, 0x9a, 0x07, 0x47, 0xed, 0x93, 0x87, 0xc7, 0x15, 0x07, 0x1f, 0x2f,
	0x11, 0x68, 0xd0, 0x21, 0xd5, 0x37, 0x56, 0x13, 0x4d, 0xa3, 0xb2, 0x28, 0x44, 0x66, 0xc2, 0x05,
	0xf3, 0x7c, 0xab, 0x69, 0xa5, 0x4a, 0x18, 0xb6, 0x6c, 0x2e, 0xb2, 0x58, 0x66, 0x89, 0x35, 0xc5,
	0x8e, 0xd5, 0x2a, 0xa3, 0x56, 0xdb, 0x0a, 0x58, 0x25, 0xab, 0xec, 0x51, 0xc2, 0x8e, 0x61, 0x6f,
	0xd5, 0xc2, 0x32, 0x79, 0x8b, 0x72, 0x37, 0x58, 0x36, 0x38, 0x27, 0x56, 0xff, 0x72, 0x5d, 0x5f,
	0xcb, 0x2c, 0x12, 0x1e, 0x7c, 0x67, 0x0e, 0x57, 0x7c, 0x5d, 0xa1, 0x11, 0xee, 0x3d, 0xe1, 0x3a,
	0x74, 0xfe, 0xa2, 0x09, 0xcf, 0x12, 0xa1, 0xbd, 0x36, 0xf1, 0xcb, 0x60, 0xc2, 0xf5, 0x3b, 0x2b,
	0x39, 0xb3, 0x02, 0xac, 0x54, 0x91, 0xc5, 0xb9, 0x92, 0x99, 0xd1, 0x5e, 0x87, 0x22, 0x5c, 0x00,
	0x58, 0x67, 0xb9, 0x8a, 0x2f, 0x46, 0xde, 0xae, 0xad, 0x33, 0x5a, 0xb0, 0x11, 0x0c, 0x96, 0x5b,
	0x2e, 0x94, 0xd9, 0x58, 0x79, 0x5d, 0x8a, 0xd6, 0xab, 0x13, 0xba, 0x46, 0xe0, 0x41, 0x6f, 0xba,
	0xc6, 0xe8, 0xa7, 0xd0, 0x8f, 0xa3, 0x35, 0x27, 0x3d, 0x72, 0xf2, 0xb8, 0x76, 0xb2, 0x4a, 0x5e,
	0x41, 0x37, 0x8e, 0x56, 0x5c, 0x7c, 0x01, 0x6c, 0xce, 0x67, 0xe9, 0x9a, 0x93, 0x3e, 0x39, 0x79,
	0x52, 0x3b, 0x59, 0xa7, 0x8c, 0xa0, 0x8f, 0x46, 0x2b, 0x8e, 0xbe, 0x84, 0xbd, 0x14, 0xf9, 0x61,
	0xcd, 0xd3, 0xa0, 0xba, 0x01, 0xe7, 0xe9, 0x1e, 0x87, 0x04, 0x83, 0x74, 0x1d, 0x62, 0x3f, 0x82,
	0x6e, 0x51, 0x66, 0xd8, 0x05, 0x8e, 0x3c, 0x19, 0x25, 0x6f, 0xb7, 0x42, 0x2b, 0xea, 0x7c, 0x06,
	0x6d, 0xa9, 0x43, 0x23, 0x53, 0x33, 0x96, 0xa9, 0xf0, 0xf6, 0xe8, 0x82, 0x40, 0xea, 0xeb, 0x0a,
	0xc1, 0xb1, 0xa6, 0x27, 0xea, 0xce, 0x95, 0x84, 0x75, 0xf5, 0x90, 0xd4, 0x7a, 0x28, 0xb0, 0x97,
	0x6e, 0x9d, 0x11, 0xab, 0xcf, 0x6e, 0x64, 0x26, 0xec, 0x18, 0x78, 0xe4, 0x88, 0xd8, 0x62, 0x97,
	0x2a, 0x61, 0x3f, 0x80, 0x96, 0x9d, 0xbd, 0x28, 0xdf, 0x27, 0x79, 0x93, 0x00, 0x14, 0xfe, 0x18,
	0xb6, 0x89, 0xee, 0xb4, 0xf7, 0x98, 0x5a, 0xaa, 0x5b, 0x1f, 0x99, 0x08, 0x32, 0xa8, 0xa4, 0xa8,
	0x37, 0x46, 0x52, 0xd2, 0x9e, 0xb7, 0xa6, 0x47, 0x5c, 0x15, 0x54, 0x52, 0x64, 0xcc, 0xaf, 0x4b,
	0x51, 0x8a, 0xd8, 0x7b, 0x42, 0x01, 0x57, 0x2b, 0x5f, 0x42, 0x0b, 0xcf, 0x67, 0x1b, 0xcb, 0x83,
	0x9d, 0x5b, 0x51, 0x68, 0xa9, 0x32, 0x37, 0xd1, 0xab, 0x25, 0x16, 0x65, 0xa4, 0x66, 0x33, 0x69,
	0xae, 0xde, 0x9c, 0x56, 0x14, 0xb7, 0x00, 0x90, 0xd9, 0x70, 0x42, 0x57, 0x9c, 0x4b, 0xdf, 0x38,
	0x66, 0x62, 0x71, 0x4b, 0xb4, 0xd3, 0x0c, 0xf0, 0xd3, 0xff, 0x39, 0xf4, 0x3e, 0x58, 0x77, 0x57,
	0xc2, 0x18, 0x7a, 0x0b, 0xbd, 0x80, 0xdd, 0x68, 0x22, 0xa2, 0x69, 0x35, 0xfe, 0x35, 0x6d, 0xdb,
	0x0c, 0x3a, 0x04, 0xda, 0xb1, 0xaf, 0xfd, 0x7f, 0x6c, 0xc1, 0xe6, 0x07, 0x29, 0xee, 0xdc, 0xe4,
	0x6a, 0x2c, 0x26, 0xd7, 0x10, 0x5a, 0x8b, 0x31, 0xb3, 0x41, 0x09, 0x18, 0xd4, 0x09, 0x70, 0x35,
	0x10, 0x2c, 0x74, 0xd8, 0x6b, 0x78, 0x32, 0x3a, 0x7f, 0x17, 0x9c, 0x9f, 0x9d, 0x5e, 0x9f, 0x8f,
	0x30, 0xf1, 0x61, 0x3d, 0x04, 0x34, 0x85, 0xdf, 0x0c, 0x1e, 0x2f, 0x14, 0x2e, 0x55, 0x52, 0xb7,
	0xb6, 0x66, 0x23, 0xd8, 0x1d, 0x0b, 0x6e, 0xca, 0x42, 0x84, 0xe3, 0x94, 0x27, 0xf8, 0xf2, 0xc0,
	0x0d, 0x9f, 0xd5, 0x1b, 0x7e, 0xa0, 0xb4, 0x5b, 0x95, 0xcf, 0x51, 0xe3, 0x3c, 0x33, 0xc5, 0x3c,
	0xe8, 0x8c, 0x97, 0x20, 0x76, 0x02, 0x8f, 0x32, 0x21, 0x62, 0x1d, 0xf2, 0x8c, 0xa7, 0x73, 0x23,
	0x23, 0x1d, 0x66, 0x65, 0x5c, 0x3d, 0x50, 0x9a, 0xc1, 0x1e, 0x09, 0x4f, 0x9d, 0xec, 0x2b, 0x14,
	0xb1, 0xdf, 0x00, 0x2b, 0xca, 0x0c, 0x9f, 0x8f, 0x54, 0x9e, 0x15, 0x61, 0x6e, 0x53, 0x2f, 0xb0,
	0x7a, 0xfb, 0xfa, 0x1e, 0x83, 0x7e, 0xa5, 0xbd, 0xb8, 0xd9, 0x5f, 0xc1, 0x20, 0xc5, 0x64, 0x9a,
	0x65, 0x07, 0x3b, 0xdf, 0xea, 0xa0, 0x67, 0x95, 0x17, 0xf6, 0x67, 0xd0, 0xaf, 0x4a, 0x21, 0xd4,
	0xd5, 0xe5, 0x79, 0x9d, 0x35, 0x7e, 0x59, 0xbb, 0xdc, 0xa0, 0x77, 0xbb, 0x76, 0xdb, 0xc7, 0xb0,
	0x47, 0xbb, 0x47, 0xa9, 0x2a, 0xe3, 0xb0, 0xd4, 0xa2, 0xa0, 0x79, 0x68, 0x5f, 0x48, 0x03, 0x14,
	0x9d, 0xa1, 0xe4, 0x7d, 0x25, 0xc0, 0x54, 0x2d, 0xe9, 0xeb, 0x68, 0x22, 0x66, 0xe2, 0x8d, 0xd2,
	0xc6, 0x6b, 0x91, 0xc5, 0x5e, 0x6d, 0x71, 0x55, 0x8b, 0xb0, 0x47, 0x97, 0x6c, 0x8c, 0xe0, 0xb3,
	0x8b, 0x11, 0xf1, 0x76, 0x2b, 0xe8, 0xd5, 0xfa, 0xd7, 0x04, 0x63, 0xc3, 0x8f, 0xb9, 0xe1, 0x69,
	0x68, 0x5f, 0xf0, 0x6d, 0xd2, 0x02, 0x82, 0xce, 0x11, 0x39, 0xf8, 0x35, 0x0c, 0xee, 0x5d, 0x27,
	0x56, 0xe1, 0x54, 0xcc, 0x5d, 0x15, 0x4e, 0xc5, 0x7c, 0x75, 0xf6, 0x37, 0xab, 0xd9, 0xff, 0x7a,
	0xe3, 0x55, 0xc3, 0xef, 0x43, 0xf7, 0x0b, 0x61, 0xb0, 0x2e, 0x02, 0xf1, 0x75, 0x29, 0xb4, 0xf1,
	0x35, 0x0c, 0xae, 0x32, 0x9e, 0xeb, 0x89, 0x32, 0x6f, 0x64, 0x32, 0x49, 0x65, 0x32, 0x31, 0xec,
	0x23, 0xe8, 0xdd, 0x88, 0x44, 0xda, 0x1b, 0x4e, 0x55, 0x72, 0x31, 0xaa, 0xdc, 0x77, 0x6b, 0xf8,
	0x12, 0x51, 0x64, 0x95, 0x6a, 0x8c, 0x58, 0x2d, 0xdb, 0x89, 0x6d, 0x8b, 0x59, 0x15, 0x06, 0x9b,
	0x46, 0xfc, 0xd1, 0xb8, 0x5e, 0xc4, 0x6f, 0xff, 0x3f, 0x0d, 0x68, 0xba, 0x5d, 0xd9, 0x73, 0xd8,
	0xc4, 0xeb, 0xa2, 0x1d, 0xda, 0x27, 0xbb, 0x2b, 0xd5, 0x1b, 0x90, 0x08, 0x93, 0x28, 0x75, 0xa8,
	0x65, 0x2c, 0x6e, 0x78, 0x81, 0xa9, 0xd4, 0xf4, 0x26, 0x21, 0xa2, 0x93, 0xfa, 0xca, 0xe2, 0x67,
	0x04, 0xe3, 0x7e, 0xf8, 0xf6, 0x70, 0xfb, 0xe1, 0x37, 0xbb, 0x00, 0xa6, 0xab, 0xed, 0xc2, 0x89,
	0x3b, 0x65, 0xfd, 0x02, 0x71, 0x1b, 0xde, 0xcb, 0x43, 0x30, 0xd0, 0xf7, 0x52, 0xf3, 0x02, 0x76,
	0x6b, 0x57, 0xa9, 0xcc, 0xa6, 0xee, 0x65, 0xe6, 0xc0, 0x4b, 0x99, 0x4d, 0xfd, 0x97, 0xb0, 0xff,
	0x3e, 0x4f, 0x15, 0x8f, 0x9d, 0xcb, 0x40, 0xe8, 0x5c, 0x65, 0x9a, 0x58, 0xa8, 0x2c, 0x52, 0x77,
	0x59, 0x65, 0x91, 0x9e, 0xfc, 0xbd, 0x01, 0x6d, 0x3c, 0xea, 0x95, 0x28, 0x6e, 0x65, 0x24, 0xd8,
	0x08, 0x76, 0xaa, 0x2b, 0x62, 0x8b, 0x29, 0xb7, 0x7a, 0x69, 0x07, 0xab, 0x49, 0xf2, 0x07, 0x7f,
	0xfa, 0xf7, 0x7f, 0xff, 0xb2, 0xd1, 0x66, 0x2d, 0xfa, 0x6b, 0x49, 0x19, 0xbb, 0x81, 0xee, 0x6a,
	0x04, 0x6c, 0x70, 0xef, 0x9c, 0x07, 0x0b, 0xa6, 0xf8, 0xe6, 0x68, 0xfd, 0xa7, 0xe4, 0x78, 0xdf,
	0x1f, 0x90, 0x63, 0x77, 0xc4, 0x61, 0x26, 0xee, 0x5e, 0x37, 0x5e, 0x7e, 0xf6, 0xf1, 0x1f, 0x3e,
	0x4a, 0xa4, 0x99, 0x94, 0x37, 0xc7, 0x91, 0x9a, 0x0d, 0xef, 0x64, 0x16, 0xcf, 0x64, 0x9a, 0x8a,
	0x2c, 0x19, 0x62, 0x61, 0x0f, 0x97, 0xfe, 0x0e, 0xdf, 0x6c, 0xd3, 0xd3, 0xe4, 0x67, 0xff, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x16, 0x46, 0x78, 0x5d, 0x24, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ViewServiceClient is the client API for ViewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ViewServiceClient interface {
	GetView(ctx context.Context, in *GetViewRequest, opts ...grpc.CallOption) (*View, error)
	UploadSnapshot(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*UploadSnapshotResponse, error)
}

type viewServiceClient struct {
	cc *grpc.ClientConn
}

func NewViewServiceClient(cc *grpc.ClientConn) ViewServiceClient {
	return &viewServiceClient{cc}
}

func (c *viewServiceClient) GetView(ctx context.Context, in *GetViewRequest, opts ...grpc.CallOption) (*View, error) {
	out := new(View)
	err := c.cc.Invoke(ctx, "/webview.ViewService/GetView", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewServiceClient) UploadSnapshot(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*UploadSnapshotResponse, error) {
	out := new(UploadSnapshotResponse)
	err := c.cc.Invoke(ctx, "/webview.ViewService/UploadSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ViewServiceServer is the server API for ViewService service.
type ViewServiceServer interface {
	GetView(context.Context, *GetViewRequest) (*View, error)
	UploadSnapshot(context.Context, *Snapshot) (*UploadSnapshotResponse, error)
}

// UnimplementedViewServiceServer can be embedded to have forward compatible implementations.
type UnimplementedViewServiceServer struct {
}

func (*UnimplementedViewServiceServer) GetView(ctx context.Context, req *GetViewRequest) (*View, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetView not implemented")
}
func (*UnimplementedViewServiceServer) UploadSnapshot(ctx context.Context, req *Snapshot) (*UploadSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadSnapshot not implemented")
}

func RegisterViewServiceServer(s *grpc.Server, srv ViewServiceServer) {
	s.RegisterService(&_ViewService_serviceDesc, srv)
}

func _ViewService_GetView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServiceServer).GetView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webview.ViewService/GetView",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServiceServer).GetView(ctx, req.(*GetViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ViewService_UploadSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Snapshot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServiceServer).UploadSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webview.ViewService/UploadSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServiceServer).UploadSnapshot(ctx, req.(*Snapshot))
	}
	return interceptor(ctx, in, info, handler)
}

var _ViewService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webview.ViewService",
	HandlerType: (*ViewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetView",
			Handler:    _ViewService_GetView_Handler,
		},
		{
			MethodName: "UploadSnapshot",
			Handler:    _ViewService_UploadSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/webview/view.proto",
}
