// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/webview/view.proto

package webview

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Correspond to implementations of the TargetSpec interface
type TargetType int32

const (
	TargetType_TARGET_TYPE_UNSPECIFIED    TargetType = 0
	TargetType_TARGET_TYPE_IMAGE          TargetType = 1
	TargetType_TARGET_TYPE_K8S            TargetType = 2
	TargetType_TARGET_TYPE_DOCKER_COMPOSE TargetType = 3
	TargetType_TARGET_TYPE_LOCAL          TargetType = 4
)

var TargetType_name = map[int32]string{
	0: "TARGET_TYPE_UNSPECIFIED",
	1: "TARGET_TYPE_IMAGE",
	2: "TARGET_TYPE_K8S",
	3: "TARGET_TYPE_DOCKER_COMPOSE",
	4: "TARGET_TYPE_LOCAL",
}

var TargetType_value = map[string]int32{
	"TARGET_TYPE_UNSPECIFIED":    0,
	"TARGET_TYPE_IMAGE":          1,
	"TARGET_TYPE_K8S":            2,
	"TARGET_TYPE_DOCKER_COMPOSE": 3,
	"TARGET_TYPE_LOCAL":          4,
}

func (x TargetType) String() string {
	return proto.EnumName(TargetType_name, int32(x))
}

func (TargetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{0}
}

type TargetSpec struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 TargetType `protobuf:"varint,2,opt,name=type,proto3,enum=webview.TargetType" json:"type,omitempty"`
	HasLiveUpdate        bool       `protobuf:"varint,3,opt,name=has_live_update,json=hasLiveUpdate,proto3" json:"has_live_update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TargetSpec) Reset()         { *m = TargetSpec{} }
func (m *TargetSpec) String() string { return proto.CompactTextString(m) }
func (*TargetSpec) ProtoMessage()    {}
func (*TargetSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{0}
}

func (m *TargetSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetSpec.Unmarshal(m, b)
}
func (m *TargetSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetSpec.Marshal(b, m, deterministic)
}
func (m *TargetSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetSpec.Merge(m, src)
}
func (m *TargetSpec) XXX_Size() int {
	return xxx_messageInfo_TargetSpec.Size(m)
}
func (m *TargetSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetSpec.DiscardUnknown(m)
}

var xxx_messageInfo_TargetSpec proto.InternalMessageInfo

func (m *TargetSpec) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TargetSpec) GetType() TargetType {
	if m != nil {
		return m.Type
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (m *TargetSpec) GetHasLiveUpdate() bool {
	if m != nil {
		return m.HasLiveUpdate
	}
	return false
}

type BuildRecord struct {
	Error          string               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Warnings       []string             `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	StartTime      *timestamp.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	FinishTime     *timestamp.Timestamp `protobuf:"bytes,5,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	IsCrashRebuild bool                 `protobuf:"varint,7,opt,name=is_crash_rebuild,json=isCrashRebuild,proto3" json:"is_crash_rebuild,omitempty"`
	// The span id for this build record's logs in the main logstore.
	SpanId               string   `protobuf:"bytes,8,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildRecord) Reset()         { *m = BuildRecord{} }
func (m *BuildRecord) String() string { return proto.CompactTextString(m) }
func (*BuildRecord) ProtoMessage()    {}
func (*BuildRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{1}
}

func (m *BuildRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRecord.Unmarshal(m, b)
}
func (m *BuildRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRecord.Marshal(b, m, deterministic)
}
func (m *BuildRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRecord.Merge(m, src)
}
func (m *BuildRecord) XXX_Size() int {
	return xxx_messageInfo_BuildRecord.Size(m)
}
func (m *BuildRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRecord.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRecord proto.InternalMessageInfo

func (m *BuildRecord) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *BuildRecord) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

func (m *BuildRecord) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *BuildRecord) GetFinishTime() *timestamp.Timestamp {
	if m != nil {
		return m.FinishTime
	}
	return nil
}

func (m *BuildRecord) GetIsCrashRebuild() bool {
	if m != nil {
		return m.IsCrashRebuild
	}
	return false
}

func (m *BuildRecord) GetSpanId() string {
	if m != nil {
		return m.SpanId
	}
	return ""
}

type K8SResourceInfo struct {
	PodName            string `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodCreationTime    string `protobuf:"bytes,2,opt,name=pod_creation_time,json=podCreationTime,proto3" json:"pod_creation_time,omitempty"`
	PodUpdateStartTime string `protobuf:"bytes,3,opt,name=pod_update_start_time,json=podUpdateStartTime,proto3" json:"pod_update_start_time,omitempty"`
	PodStatus          string `protobuf:"bytes,4,opt,name=pod_status,json=podStatus,proto3" json:"pod_status,omitempty"`
	PodStatusMessage   string `protobuf:"bytes,5,opt,name=pod_status_message,json=podStatusMessage,proto3" json:"pod_status_message,omitempty"`
	AllContainersReady bool   `protobuf:"varint,6,opt,name=all_containers_ready,json=allContainersReady,proto3" json:"all_containers_ready,omitempty"`
	PodRestarts        int32  `protobuf:"varint,7,opt,name=pod_restarts,json=podRestarts,proto3" json:"pod_restarts,omitempty"`
	// The span id for this pod's logs in the main logstore
	SpanId               string   `protobuf:"bytes,9,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	DisplayNames         []string `protobuf:"bytes,10,rep,name=display_names,json=displayNames,proto3" json:"display_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *K8SResourceInfo) Reset()         { *m = K8SResourceInfo{} }
func (m *K8SResourceInfo) String() string { return proto.CompactTextString(m) }
func (*K8SResourceInfo) ProtoMessage()    {}
func (*K8SResourceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{2}
}

func (m *K8SResourceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_K8SResourceInfo.Unmarshal(m, b)
}
func (m *K8SResourceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_K8SResourceInfo.Marshal(b, m, deterministic)
}
func (m *K8SResourceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_K8SResourceInfo.Merge(m, src)
}
func (m *K8SResourceInfo) XXX_Size() int {
	return xxx_messageInfo_K8SResourceInfo.Size(m)
}
func (m *K8SResourceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_K8SResourceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_K8SResourceInfo proto.InternalMessageInfo

func (m *K8SResourceInfo) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *K8SResourceInfo) GetPodCreationTime() string {
	if m != nil {
		return m.PodCreationTime
	}
	return ""
}

func (m *K8SResourceInfo) GetPodUpdateStartTime() string {
	if m != nil {
		return m.PodUpdateStartTime
	}
	return ""
}

func (m *K8SResourceInfo) GetPodStatus() string {
	if m != nil {
		return m.PodStatus
	}
	return ""
}

func (m *K8SResourceInfo) GetPodStatusMessage() string {
	if m != nil {
		return m.PodStatusMessage
	}
	return ""
}

func (m *K8SResourceInfo) GetAllContainersReady() bool {
	if m != nil {
		return m.AllContainersReady
	}
	return false
}

func (m *K8SResourceInfo) GetPodRestarts() int32 {
	if m != nil {
		return m.PodRestarts
	}
	return 0
}

func (m *K8SResourceInfo) GetSpanId() string {
	if m != nil {
		return m.SpanId
	}
	return ""
}

func (m *K8SResourceInfo) GetDisplayNames() []string {
	if m != nil {
		return m.DisplayNames
	}
	return nil
}

type LocalResourceInfo struct {
	Pid                  int64    `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	IsTest               bool     `protobuf:"varint,2,opt,name=is_test,json=isTest,proto3" json:"is_test,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalResourceInfo) Reset()         { *m = LocalResourceInfo{} }
func (m *LocalResourceInfo) String() string { return proto.CompactTextString(m) }
func (*LocalResourceInfo) ProtoMessage()    {}
func (*LocalResourceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{3}
}

func (m *LocalResourceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalResourceInfo.Unmarshal(m, b)
}
func (m *LocalResourceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalResourceInfo.Marshal(b, m, deterministic)
}
func (m *LocalResourceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalResourceInfo.Merge(m, src)
}
func (m *LocalResourceInfo) XXX_Size() int {
	return xxx_messageInfo_LocalResourceInfo.Size(m)
}
func (m *LocalResourceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalResourceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LocalResourceInfo proto.InternalMessageInfo

func (m *LocalResourceInfo) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *LocalResourceInfo) GetIsTest() bool {
	if m != nil {
		return m.IsTest
	}
	return false
}

type Link struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Link) Reset()         { *m = Link{} }
func (m *Link) String() string { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()    {}
func (*Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{4}
}

func (m *Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link.Unmarshal(m, b)
}
func (m *Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link.Marshal(b, m, deterministic)
}
func (m *Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link.Merge(m, src)
}
func (m *Link) XXX_Size() int {
	return xxx_messageInfo_Link.Size(m)
}
func (m *Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Link proto.InternalMessageInfo

func (m *Link) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Link) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Resource struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LastDeployTime       *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_deploy_time,json=lastDeployTime,proto3" json:"last_deploy_time,omitempty"`
	TriggerMode          int32                `protobuf:"varint,5,opt,name=trigger_mode,json=triggerMode,proto3" json:"trigger_mode,omitempty"`
	BuildHistory         []*BuildRecord       `protobuf:"bytes,6,rep,name=build_history,json=buildHistory,proto3" json:"build_history,omitempty"`
	CurrentBuild         *BuildRecord         `protobuf:"bytes,7,opt,name=current_build,json=currentBuild,proto3" json:"current_build,omitempty"`
	PendingBuildSince    *timestamp.Timestamp `protobuf:"bytes,10,opt,name=pending_build_since,json=pendingBuildSince,proto3" json:"pending_build_since,omitempty"`
	HasPendingChanges    bool                 `protobuf:"varint,11,opt,name=has_pending_changes,json=hasPendingChanges,proto3" json:"has_pending_changes,omitempty"`
	EndpointLinks        []*Link              `protobuf:"bytes,28,rep,name=endpoint_links,json=endpointLinks,proto3" json:"endpoint_links,omitempty"`
	PodID                string               `protobuf:"bytes,13,opt,name=podID,proto3" json:"podID,omitempty"`
	K8SResourceInfo      *K8SResourceInfo     `protobuf:"bytes,14,opt,name=k8s_resource_info,json=k8sResourceInfo,proto3" json:"k8s_resource_info,omitempty"`
	LocalResourceInfo    *LocalResourceInfo   `protobuf:"bytes,17,opt,name=local_resource_info,json=localResourceInfo,proto3" json:"local_resource_info,omitempty"`
	RuntimeStatus        string               `protobuf:"bytes,18,opt,name=runtime_status,json=runtimeStatus,proto3" json:"runtime_status,omitempty"`
	UpdateStatus         string               `protobuf:"bytes,29,opt,name=update_status,json=updateStatus,proto3" json:"update_status,omitempty"`
	IsTiltfile           bool                 `protobuf:"varint,19,opt,name=is_tiltfile,json=isTiltfile,proto3" json:"is_tiltfile,omitempty"`
	Specs                []*TargetSpec        `protobuf:"bytes,27,rep,name=specs,proto3" json:"specs,omitempty"`
	Queued               bool                 `protobuf:"varint,25,opt,name=queued,proto3" json:"queued,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{5}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetLastDeployTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastDeployTime
	}
	return nil
}

func (m *Resource) GetTriggerMode() int32 {
	if m != nil {
		return m.TriggerMode
	}
	return 0
}

func (m *Resource) GetBuildHistory() []*BuildRecord {
	if m != nil {
		return m.BuildHistory
	}
	return nil
}

func (m *Resource) GetCurrentBuild() *BuildRecord {
	if m != nil {
		return m.CurrentBuild
	}
	return nil
}

func (m *Resource) GetPendingBuildSince() *timestamp.Timestamp {
	if m != nil {
		return m.PendingBuildSince
	}
	return nil
}

func (m *Resource) GetHasPendingChanges() bool {
	if m != nil {
		return m.HasPendingChanges
	}
	return false
}

func (m *Resource) GetEndpointLinks() []*Link {
	if m != nil {
		return m.EndpointLinks
	}
	return nil
}

func (m *Resource) GetPodID() string {
	if m != nil {
		return m.PodID
	}
	return ""
}

func (m *Resource) GetK8SResourceInfo() *K8SResourceInfo {
	if m != nil {
		return m.K8SResourceInfo
	}
	return nil
}

func (m *Resource) GetLocalResourceInfo() *LocalResourceInfo {
	if m != nil {
		return m.LocalResourceInfo
	}
	return nil
}

func (m *Resource) GetRuntimeStatus() string {
	if m != nil {
		return m.RuntimeStatus
	}
	return ""
}

func (m *Resource) GetUpdateStatus() string {
	if m != nil {
		return m.UpdateStatus
	}
	return ""
}

func (m *Resource) GetIsTiltfile() bool {
	if m != nil {
		return m.IsTiltfile
	}
	return false
}

func (m *Resource) GetSpecs() []*TargetSpec {
	if m != nil {
		return m.Specs
	}
	return nil
}

func (m *Resource) GetQueued() bool {
	if m != nil {
		return m.Queued
	}
	return false
}

type TiltBuild struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	CommitSHA            string   `protobuf:"bytes,2,opt,name=commitSHA,proto3" json:"commitSHA,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Dev                  bool     `protobuf:"varint,4,opt,name=dev,proto3" json:"dev,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TiltBuild) Reset()         { *m = TiltBuild{} }
func (m *TiltBuild) String() string { return proto.CompactTextString(m) }
func (*TiltBuild) ProtoMessage()    {}
func (*TiltBuild) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{6}
}

func (m *TiltBuild) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TiltBuild.Unmarshal(m, b)
}
func (m *TiltBuild) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TiltBuild.Marshal(b, m, deterministic)
}
func (m *TiltBuild) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TiltBuild.Merge(m, src)
}
func (m *TiltBuild) XXX_Size() int {
	return xxx_messageInfo_TiltBuild.Size(m)
}
func (m *TiltBuild) XXX_DiscardUnknown() {
	xxx_messageInfo_TiltBuild.DiscardUnknown(m)
}

var xxx_messageInfo_TiltBuild proto.InternalMessageInfo

func (m *TiltBuild) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *TiltBuild) GetCommitSHA() string {
	if m != nil {
		return m.CommitSHA
	}
	return ""
}

func (m *TiltBuild) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *TiltBuild) GetDev() bool {
	if m != nil {
		return m.Dev
	}
	return false
}

type VersionSettings struct {
	CheckUpdates         bool     `protobuf:"varint,1,opt,name=check_updates,json=checkUpdates,proto3" json:"check_updates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionSettings) Reset()         { *m = VersionSettings{} }
func (m *VersionSettings) String() string { return proto.CompactTextString(m) }
func (*VersionSettings) ProtoMessage()    {}
func (*VersionSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{7}
}

func (m *VersionSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionSettings.Unmarshal(m, b)
}
func (m *VersionSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionSettings.Marshal(b, m, deterministic)
}
func (m *VersionSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionSettings.Merge(m, src)
}
func (m *VersionSettings) XXX_Size() int {
	return xxx_messageInfo_VersionSettings.Size(m)
}
func (m *VersionSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionSettings.DiscardUnknown(m)
}

var xxx_messageInfo_VersionSettings proto.InternalMessageInfo

func (m *VersionSettings) GetCheckUpdates() bool {
	if m != nil {
		return m.CheckUpdates
	}
	return false
}

type View struct {
	Log       string      `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	Resources []*Resource `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	// We used to have a setting that allowed users to dynamically
	// prepend timestamps in logs.
	DEPRECATEDLogTimestamps   bool             `protobuf:"varint,3,opt,name=DEPRECATED_log_timestamps,json=DEPRECATEDLogTimestamps,proto3" json:"DEPRECATED_log_timestamps,omitempty"`
	FeatureFlags              map[string]bool  `protobuf:"bytes,4,rep,name=feature_flags,json=featureFlags,proto3" json:"feature_flags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	NeedsAnalyticsNudge       bool             `protobuf:"varint,5,opt,name=needs_analytics_nudge,json=needsAnalyticsNudge,proto3" json:"needs_analytics_nudge,omitempty"`
	RunningTiltBuild          *TiltBuild       `protobuf:"bytes,6,opt,name=running_tilt_build,json=runningTiltBuild,proto3" json:"running_tilt_build,omitempty"`
	DEPRECATEDLatestTiltBuild *TiltBuild       `protobuf:"bytes,7,opt,name=DEPRECATED_latest_tilt_build,json=DEPRECATEDLatestTiltBuild,proto3" json:"DEPRECATED_latest_tilt_build,omitempty"`
	SuggestedTiltVersion      string           `protobuf:"bytes,16,opt,name=suggested_tilt_version,json=suggestedTiltVersion,proto3" json:"suggested_tilt_version,omitempty"`
	VersionSettings           *VersionSettings `protobuf:"bytes,12,opt,name=version_settings,json=versionSettings,proto3" json:"version_settings,omitempty"`
	TiltCloudUsername         string           `protobuf:"bytes,8,opt,name=tilt_cloud_username,json=tiltCloudUsername,proto3" json:"tilt_cloud_username,omitempty"`
	TiltCloudTeamName         string           `protobuf:"bytes,15,opt,name=tilt_cloud_team_name,json=tiltCloudTeamName,proto3" json:"tilt_cloud_team_name,omitempty"`
	TiltCloudSchemeHost       string           `protobuf:"bytes,9,opt,name=tilt_cloud_schemeHost,json=tiltCloudSchemeHost,proto3" json:"tilt_cloud_schemeHost,omitempty"`
	TiltCloudTeamID           string           `protobuf:"bytes,10,opt,name=tilt_cloud_teamID,json=tiltCloudTeamID,proto3" json:"tilt_cloud_teamID,omitempty"`
	FatalError                string           `protobuf:"bytes,11,opt,name=fatal_error,json=fatalError,proto3" json:"fatal_error,omitempty"`
	LogList                   *LogList         `protobuf:"bytes,13,opt,name=log_list,json=logList,proto3" json:"log_list,omitempty"`
	// Allows us to synchronize on a running Tilt intance,
	// so we can tell when Tilt restarted.
	TiltStartTime *timestamp.Timestamp `protobuf:"bytes,14,opt,name=tilt_start_time,json=tiltStartTime,proto3" json:"tilt_start_time,omitempty"`
	// an identifier for the tiltfile that is running, so that the web ui can store data per tiltfile
	TiltfileKey          string   `protobuf:"bytes,17,opt,name=tiltfile_key,json=tiltfileKey,proto3" json:"tiltfile_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *View) Reset()         { *m = View{} }
func (m *View) String() string { return proto.CompactTextString(m) }
func (*View) ProtoMessage()    {}
func (*View) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{8}
}

func (m *View) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_View.Unmarshal(m, b)
}
func (m *View) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_View.Marshal(b, m, deterministic)
}
func (m *View) XXX_Merge(src proto.Message) {
	xxx_messageInfo_View.Merge(m, src)
}
func (m *View) XXX_Size() int {
	return xxx_messageInfo_View.Size(m)
}
func (m *View) XXX_DiscardUnknown() {
	xxx_messageInfo_View.DiscardUnknown(m)
}

var xxx_messageInfo_View proto.InternalMessageInfo

func (m *View) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *View) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *View) GetDEPRECATEDLogTimestamps() bool {
	if m != nil {
		return m.DEPRECATEDLogTimestamps
	}
	return false
}

func (m *View) GetFeatureFlags() map[string]bool {
	if m != nil {
		return m.FeatureFlags
	}
	return nil
}

func (m *View) GetNeedsAnalyticsNudge() bool {
	if m != nil {
		return m.NeedsAnalyticsNudge
	}
	return false
}

func (m *View) GetRunningTiltBuild() *TiltBuild {
	if m != nil {
		return m.RunningTiltBuild
	}
	return nil
}

func (m *View) GetDEPRECATEDLatestTiltBuild() *TiltBuild {
	if m != nil {
		return m.DEPRECATEDLatestTiltBuild
	}
	return nil
}

func (m *View) GetSuggestedTiltVersion() string {
	if m != nil {
		return m.SuggestedTiltVersion
	}
	return ""
}

func (m *View) GetVersionSettings() *VersionSettings {
	if m != nil {
		return m.VersionSettings
	}
	return nil
}

func (m *View) GetTiltCloudUsername() string {
	if m != nil {
		return m.TiltCloudUsername
	}
	return ""
}

func (m *View) GetTiltCloudTeamName() string {
	if m != nil {
		return m.TiltCloudTeamName
	}
	return ""
}

func (m *View) GetTiltCloudSchemeHost() string {
	if m != nil {
		return m.TiltCloudSchemeHost
	}
	return ""
}

func (m *View) GetTiltCloudTeamID() string {
	if m != nil {
		return m.TiltCloudTeamID
	}
	return ""
}

func (m *View) GetFatalError() string {
	if m != nil {
		return m.FatalError
	}
	return ""
}

func (m *View) GetLogList() *LogList {
	if m != nil {
		return m.LogList
	}
	return nil
}

func (m *View) GetTiltStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.TiltStartTime
	}
	return nil
}

func (m *View) GetTiltfileKey() string {
	if m != nil {
		return m.TiltfileKey
	}
	return ""
}

type MetricsServing struct {
	// Whether we're using the local or remote metrics stack.
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// e.g., "localhost:10352"
	GrafanaHost          string   `protobuf:"bytes,2,opt,name=grafana_host,json=grafanaHost,proto3" json:"grafana_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricsServing) Reset()         { *m = MetricsServing{} }
func (m *MetricsServing) String() string { return proto.CompactTextString(m) }
func (*MetricsServing) ProtoMessage()    {}
func (*MetricsServing) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{9}
}

func (m *MetricsServing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsServing.Unmarshal(m, b)
}
func (m *MetricsServing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsServing.Marshal(b, m, deterministic)
}
func (m *MetricsServing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsServing.Merge(m, src)
}
func (m *MetricsServing) XXX_Size() int {
	return xxx_messageInfo_MetricsServing.Size(m)
}
func (m *MetricsServing) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsServing.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsServing proto.InternalMessageInfo

func (m *MetricsServing) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *MetricsServing) GetGrafanaHost() string {
	if m != nil {
		return m.GrafanaHost
	}
	return ""
}

type GetViewRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetViewRequest) Reset()         { *m = GetViewRequest{} }
func (m *GetViewRequest) String() string { return proto.CompactTextString(m) }
func (*GetViewRequest) ProtoMessage()    {}
func (*GetViewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{10}
}

func (m *GetViewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetViewRequest.Unmarshal(m, b)
}
func (m *GetViewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetViewRequest.Marshal(b, m, deterministic)
}
func (m *GetViewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetViewRequest.Merge(m, src)
}
func (m *GetViewRequest) XXX_Size() int {
	return xxx_messageInfo_GetViewRequest.Size(m)
}
func (m *GetViewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetViewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetViewRequest proto.InternalMessageInfo

type SnapshotHighlight struct {
	BeginningLogID       string   `protobuf:"bytes,1,opt,name=beginning_logID,json=beginningLogID,proto3" json:"beginning_logID,omitempty"`
	EndingLogID          string   `protobuf:"bytes,2,opt,name=ending_logID,json=endingLogID,proto3" json:"ending_logID,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotHighlight) Reset()         { *m = SnapshotHighlight{} }
func (m *SnapshotHighlight) String() string { return proto.CompactTextString(m) }
func (*SnapshotHighlight) ProtoMessage()    {}
func (*SnapshotHighlight) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{11}
}

func (m *SnapshotHighlight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotHighlight.Unmarshal(m, b)
}
func (m *SnapshotHighlight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotHighlight.Marshal(b, m, deterministic)
}
func (m *SnapshotHighlight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotHighlight.Merge(m, src)
}
func (m *SnapshotHighlight) XXX_Size() int {
	return xxx_messageInfo_SnapshotHighlight.Size(m)
}
func (m *SnapshotHighlight) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotHighlight.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotHighlight proto.InternalMessageInfo

func (m *SnapshotHighlight) GetBeginningLogID() string {
	if m != nil {
		return m.BeginningLogID
	}
	return ""
}

func (m *SnapshotHighlight) GetEndingLogID() string {
	if m != nil {
		return m.EndingLogID
	}
	return ""
}

func (m *SnapshotHighlight) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Snapshot struct {
	View                 *View              `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	IsSidebarClosed      bool               `protobuf:"varint,2,opt,name=is_sidebar_closed,json=isSidebarClosed,proto3" json:"is_sidebar_closed,omitempty"`
	Path                 string             `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	SnapshotHighlight    *SnapshotHighlight `protobuf:"bytes,4,opt,name=snapshot_highlight,json=snapshotHighlight,proto3" json:"snapshot_highlight,omitempty"`
	SnapshotLink         string             `protobuf:"bytes,5,opt,name=snapshot_link,json=snapshotLink,proto3" json:"snapshot_link,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{12}
}

func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetView() *View {
	if m != nil {
		return m.View
	}
	return nil
}

func (m *Snapshot) GetIsSidebarClosed() bool {
	if m != nil {
		return m.IsSidebarClosed
	}
	return false
}

func (m *Snapshot) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Snapshot) GetSnapshotHighlight() *SnapshotHighlight {
	if m != nil {
		return m.SnapshotHighlight
	}
	return nil
}

func (m *Snapshot) GetSnapshotLink() string {
	if m != nil {
		return m.SnapshotLink
	}
	return ""
}

type UploadSnapshotResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadSnapshotResponse) Reset()         { *m = UploadSnapshotResponse{} }
func (m *UploadSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*UploadSnapshotResponse) ProtoMessage()    {}
func (*UploadSnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{13}
}

func (m *UploadSnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadSnapshotResponse.Unmarshal(m, b)
}
func (m *UploadSnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadSnapshotResponse.Marshal(b, m, deterministic)
}
func (m *UploadSnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadSnapshotResponse.Merge(m, src)
}
func (m *UploadSnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_UploadSnapshotResponse.Size(m)
}
func (m *UploadSnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadSnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadSnapshotResponse proto.InternalMessageInfo

func (m *UploadSnapshotResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// The webclient needs to notify the server what logs it has,
// so the server knows what to send.
//
// The socket protocol doesn't have any concept of a StatusCode
// to confirm that the receiver got the message, so we need to send this
// in a separate message.
type AckWebsocketRequest struct {
	// The to_checkpoint on the received LogList
	ToCheckpoint int32 `protobuf:"varint,1,opt,name=to_checkpoint,json=toCheckpoint,proto3" json:"to_checkpoint,omitempty"`
	// Allows us to synchronize on a running Tilt intance,
	// so we can tell when we're talking to the same Tilt.
	TiltStartTime        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=tilt_start_time,json=tiltStartTime,proto3" json:"tilt_start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AckWebsocketRequest) Reset()         { *m = AckWebsocketRequest{} }
func (m *AckWebsocketRequest) String() string { return proto.CompactTextString(m) }
func (*AckWebsocketRequest) ProtoMessage()    {}
func (*AckWebsocketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{14}
}

func (m *AckWebsocketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckWebsocketRequest.Unmarshal(m, b)
}
func (m *AckWebsocketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckWebsocketRequest.Marshal(b, m, deterministic)
}
func (m *AckWebsocketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckWebsocketRequest.Merge(m, src)
}
func (m *AckWebsocketRequest) XXX_Size() int {
	return xxx_messageInfo_AckWebsocketRequest.Size(m)
}
func (m *AckWebsocketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AckWebsocketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AckWebsocketRequest proto.InternalMessageInfo

func (m *AckWebsocketRequest) GetToCheckpoint() int32 {
	if m != nil {
		return m.ToCheckpoint
	}
	return 0
}

func (m *AckWebsocketRequest) GetTiltStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.TiltStartTime
	}
	return nil
}

type AckWebsocketResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckWebsocketResponse) Reset()         { *m = AckWebsocketResponse{} }
func (m *AckWebsocketResponse) String() string { return proto.CompactTextString(m) }
func (*AckWebsocketResponse) ProtoMessage()    {}
func (*AckWebsocketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961ad0c6909086c3, []int{15}
}

func (m *AckWebsocketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckWebsocketResponse.Unmarshal(m, b)
}
func (m *AckWebsocketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckWebsocketResponse.Marshal(b, m, deterministic)
}
func (m *AckWebsocketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckWebsocketResponse.Merge(m, src)
}
func (m *AckWebsocketResponse) XXX_Size() int {
	return xxx_messageInfo_AckWebsocketResponse.Size(m)
}
func (m *AckWebsocketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckWebsocketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckWebsocketResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("webview.TargetType", TargetType_name, TargetType_value)
	proto.RegisterType((*TargetSpec)(nil), "webview.TargetSpec")
	proto.RegisterType((*BuildRecord)(nil), "webview.BuildRecord")
	proto.RegisterType((*K8SResourceInfo)(nil), "webview.K8sResourceInfo")
	proto.RegisterType((*LocalResourceInfo)(nil), "webview.LocalResourceInfo")
	proto.RegisterType((*Link)(nil), "webview.Link")
	proto.RegisterType((*Resource)(nil), "webview.Resource")
	proto.RegisterType((*TiltBuild)(nil), "webview.TiltBuild")
	proto.RegisterType((*VersionSettings)(nil), "webview.VersionSettings")
	proto.RegisterType((*View)(nil), "webview.View")
	proto.RegisterMapType((map[string]bool)(nil), "webview.View.FeatureFlagsEntry")
	proto.RegisterType((*MetricsServing)(nil), "webview.MetricsServing")
	proto.RegisterType((*GetViewRequest)(nil), "webview.GetViewRequest")
	proto.RegisterType((*SnapshotHighlight)(nil), "webview.SnapshotHighlight")
	proto.RegisterType((*Snapshot)(nil), "webview.Snapshot")
	proto.RegisterType((*UploadSnapshotResponse)(nil), "webview.UploadSnapshotResponse")
	proto.RegisterType((*AckWebsocketRequest)(nil), "webview.AckWebsocketRequest")
	proto.RegisterType((*AckWebsocketResponse)(nil), "webview.AckWebsocketResponse")
}

func init() { proto.RegisterFile("pkg/webview/view.proto", fileDescriptor_961ad0c6909086c3) }

var fileDescriptor_961ad0c6909086c3 = []byte{
	// 2068 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xcb, 0x72, 0x23, 0x49,
	0xd5, 0xfe, 0x25, 0x97, 0xed, 0xd2, 0xd1, 0xad, 0x94, 0xf2, 0xa5, 0xda, 0xe3, 0xf9, 0xa7, 0x47,
	0x0d, 0x33, 0xa6, 0x19, 0x2c, 0x30, 0x13, 0x44, 0x4f, 0x13, 0x01, 0x78, 0x24, 0x4d, 0xb7, 0xd5,
	0xee, 0x4b, 0xa4, 0xdc, 0x43, 0xc0, 0xa6, 0x22, 0x5d, 0x95, 0x2a, 0x65, 0xb8, 0x54, 0x59, 0x53,
	0x99, 0xb2, 0x31, 0x0b, 0x16, 0xac, 0xd9, 0xf1, 0x0a, 0x04, 0xaf, 0xc0, 0x83, 0xb0, 0x26, 0xd8,
	0xf0, 0x14, 0xac, 0x88, 0xbc, 0x54, 0x49, 0x96, 0xbb, 0xa3, 0x61, 0xe3, 0xc8, 0x3c, 0xd7, 0xca,
	0x73, 0xbe, 0x73, 0x91, 0x61, 0x2f, 0xbb, 0x8a, 0xfb, 0x37, 0xf4, 0xf2, 0x9a, 0xd1, 0x9b, 0xbe,
	0xfa, 0x73, 0x9c, 0xe5, 0x5c, 0x72, 0xb4, 0x6d, 0x69, 0x07, 0x87, 0x31, 0xe7, 0x71, 0x42, 0xfb,
	0x24, 0x63, 0x7d, 0x92, 0xa6, 0x5c, 0x12, 0xc9, 0x78, 0x2a, 0x8c, 0xd8, 0xc1, 0x27, 0x96, 0xab,
	0x6f, 0x97, 0x8b, 0x69, 0x5f, 0xb2, 0x39, 0x15, 0x92, 0xcc, 0x33, 0x2b, 0xb0, 0xbb, 0x6a, 0x3f,
	0xe1, 0xb1, 0x21, 0xf7, 0xe6, 0x00, 0x17, 0x24, 0x8f, 0xa9, 0x9c, 0x64, 0x34, 0x44, 0x2d, 0xa8,
	0xb2, 0xc8, 0xaf, 0x3c, 0xac, 0x1c, 0xd5, 0x70, 0x95, 0x45, 0xe8, 0x73, 0x70, 0xe4, 0x6d, 0x46,
	0xfd, 0xea, 0xc3, 0xca, 0x51, 0xeb, 0xa4, 0x7b, 0x6c, 0xf5, 0x8f, 0x8d, 0xca, 0xc5, 0x6d, 0x46,
	0xb1, 0x16, 0x40, 0x9f, 0x41, 0x7b, 0x46, 0x44, 0x90, 0xb0, 0x6b, 0x1a, 0x2c, 0xb2, 0x88, 0x48,
	0xea, 0x6f, 0x3c, 0xac, 0x1c, 0xb9, 0xb8, 0x39, 0x23, 0xe2, 0x9c, 0x5d, 0xd3, 0xb7, 0x9a, 0xd8,
	0xfb, 0x6b, 0x15, 0xea, 0x5f, 0x2f, 0x58, 0x12, 0x61, 0x1a, 0xf2, 0x3c, 0x42, 0x3b, 0xb0, 0x49,
	0xf3, 0x9c, 0xe7, 0xda, 0x43, 0x0d, 0x9b, 0x0b, 0x3a, 0x00, 0xf7, 0x86, 0xe4, 0x29, 0x4b, 0x63,
	0xe1, 0x6f, 0x3c, 0xdc, 0x38, 0xaa, 0xe1, 0xf2, 0x8e, 0xbe, 0x02, 0x10, 0x92, 0xe4, 0x32, 0x50,
	0x0f, 0xf4, 0x9d, 0x87, 0x95, 0xa3, 0xfa, 0xc9, 0xc1, 0xb1, 0x79, 0xfd, 0x71, 0xf1, 0xfa, 0xe3,
	0x8b, 0xe2, 0xf5, 0xb8, 0xa6, 0xa5, 0xd5, 0x1d, 0xfd, 0x1c, 0xea, 0x53, 0x96, 0x32, 0x31, 0x33,
	0xba, 0x9b, 0x1f, 0xd4, 0x05, 0x23, 0xae, 0x95, 0x8f, 0xc0, 0x63, 0x22, 0x08, 0x73, 0x22, 0x66,
	0x41, 0x4e, 0x2f, 0xd5, 0x1b, 0xfc, 0x6d, 0xfd, 0xc4, 0x16, 0x13, 0x03, 0x45, 0xc6, 0x86, 0x8a,
	0xf6, 0x61, 0x5b, 0x64, 0x24, 0x0d, 0x58, 0xe4, 0xbb, 0xfa, 0x55, 0x5b, 0xea, 0x7a, 0x16, 0x8d,
	0x1d, 0xb7, 0xe2, 0x55, 0xc7, 0x8e, 0x5b, 0xf3, 0x60, 0xec, 0xb8, 0x5b, 0xde, 0x36, 0xde, 0xa4,
	0x11, 0x93, 0x02, 0x37, 0x4c, 0xc8, 0x02, 0x15, 0x4a, 0x81, 0x37, 0x12, 0x1e, 0xf7, 0xfe, 0x5d,
	0x85, 0xf6, 0x8b, 0x27, 0x02, 0x53, 0xc1, 0x17, 0x79, 0x48, 0xcf, 0xd2, 0x29, 0x47, 0x0f, 0xc0,
	0xcd, 0x78, 0x14, 0xa4, 0x64, 0x4e, 0x6d, 0x8e, 0xb6, 0x33, 0x1e, 0xbd, 0x22, 0x73, 0x8a, 0x1e,
	0x43, 0x47, 0xb1, 0xc2, 0x9c, 0x6a, 0x54, 0x98, 0x07, 0x9a, 0x98, 0xb6, 0x33, 0x1e, 0x0d, 0x2c,
	0x5d, 0xbf, 0xe4, 0x27, 0xb0, 0xab, 0x64, 0xad, 0xcf, 0x95, 0x60, 0x6e, 0x68, 0x79, 0x94, 0xf1,
	0xc8, 0x64, 0x6b, 0x52, 0x46, 0xee, 0x63, 0x00, 0xa5, 0x22, 0x24, 0x91, 0x0b, 0xa1, 0x83, 0x5e,
	0xc3, 0xb5, 0x8c, 0x47, 0x13, 0x4d, 0x40, 0x5f, 0x00, 0x5a, 0xb2, 0x83, 0x39, 0x15, 0x82, 0xc4,
	0x26, 0xbe, 0x35, 0xec, 0x95, 0x62, 0x2f, 0x0d, 0x1d, 0xfd, 0x18, 0x76, 0x48, 0x92, 0x04, 0x21,
	0x4f, 0x25, 0x61, 0x29, 0xcd, 0x45, 0x90, 0x53, 0x12, 0xdd, 0xfa, 0x5b, 0x3a, 0x9a, 0x88, 0x24,
	0xc9, 0xa0, 0x64, 0x61, 0xc5, 0x41, 0x9f, 0x42, 0x43, 0xd9, 0xcf, 0xa9, 0xfe, 0x58, 0xa1, 0xe3,
	0xbe, 0x89, 0xeb, 0x19, 0x8f, 0xb0, 0x25, 0xad, 0x06, 0xbd, 0xb6, 0x1a, 0x74, 0xf4, 0x08, 0x9a,
	0x11, 0x13, 0x59, 0x42, 0x6e, 0x75, 0xe0, 0x84, 0x0f, 0x1a, 0x50, 0x0d, 0x4b, 0x54, 0xd1, 0x13,
	0x63, 0xc7, 0x75, 0x3d, 0x13, 0xcd, 0x40, 0x05, 0xff, 0x17, 0xd0, 0x39, 0xe7, 0x21, 0x49, 0xee,
	0x44, 0xdf, 0x83, 0x8d, 0xcc, 0x16, 0xc7, 0x06, 0x56, 0x47, 0xe5, 0x93, 0x89, 0x40, 0x52, 0x21,
	0x75, 0xa8, 0x5d, 0xbc, 0xc5, 0xc4, 0x05, 0x15, 0xb2, 0xf7, 0x05, 0x38, 0xe7, 0x2c, 0xbd, 0x52,
	0x2a, 0x8b, 0x3c, 0xb1, 0xb9, 0x52, 0x47, 0x84, 0xc0, 0xd1, 0xe9, 0x33, 0xa9, 0xd1, 0xe7, 0xde,
	0x5f, 0x5c, 0x70, 0x0b, 0x4f, 0xa5, 0x40, 0x65, 0x29, 0x80, 0x86, 0xe0, 0x25, 0x44, 0xc8, 0x20,
	0xa2, 0x59, 0xc2, 0x6f, 0xff, 0x5b, 0xe0, 0xb7, 0x94, 0xce, 0x50, 0xab, 0xe8, 0x1c, 0x7e, 0x0a,
	0x0d, 0x99, 0xb3, 0x38, 0xa6, 0x79, 0x30, 0xe7, 0x91, 0x49, 0xcf, 0x26, 0xae, 0x5b, 0xda, 0x4b,
	0x1e, 0x51, 0xf4, 0x15, 0x34, 0x35, 0x84, 0x83, 0x19, 0x13, 0x92, 0xe7, 0x2a, 0x25, 0x1b, 0x47,
	0xf5, 0x93, 0x9d, 0xb2, 0xee, 0x57, 0x4a, 0x17, 0x37, 0xb4, 0xe8, 0x73, 0x23, 0xa9, 0x54, 0xc3,
	0x45, 0x9e, 0xd3, 0x54, 0x06, 0xcb, 0xda, 0x78, 0xaf, 0xaa, 0x15, 0xd5, 0x34, 0x34, 0x86, 0x6e,
	0x46, 0xd3, 0x88, 0xa5, 0xb1, 0x51, 0x0d, 0x04, 0x4b, 0x43, 0xea, 0xc3, 0x07, 0x5f, 0xd8, 0xb1,
	0x6a, 0xda, 0xcc, 0x44, 0x29, 0xa1, 0x63, 0xe8, 0xaa, 0x3e, 0x54, 0xd8, 0x0b, 0x67, 0x24, 0x8d,
	0xa9, 0xf0, 0xeb, 0x3a, 0x3d, 0x9d, 0x19, 0x11, 0x6f, 0x0c, 0x67, 0x60, 0x18, 0xe8, 0x4b, 0x68,
	0xd1, 0x34, 0xca, 0x38, 0x4b, 0x65, 0x90, 0xb0, 0xf4, 0x4a, 0xf8, 0x87, 0xfa, 0xc9, 0xcd, 0xf2,
	0xbb, 0x55, 0x22, 0x71, 0xb3, 0x10, 0x52, 0x37, 0xa1, 0xba, 0x56, 0xc6, 0xa3, 0xb3, 0xa1, 0xdf,
	0x34, 0x5d, 0x4b, 0x5f, 0xd0, 0x10, 0x3a, 0x57, 0x4f, 0x14, 0x98, 0x4d, 0x2a, 0x03, 0x96, 0x4e,
	0xb9, 0xdf, 0xd2, 0xaf, 0xf0, 0x4b, 0x73, 0x6b, 0x35, 0x8d, 0xdb, 0x57, 0x6b, 0x45, 0x3e, 0x86,
	0x6e, 0xa2, 0xb0, 0xb7, 0x66, 0xa7, 0x63, 0xa3, 0x51, 0x7e, 0xd6, 0x3a, 0x3e, 0x71, 0x27, 0xb9,
	0x07, 0xd9, 0xef, 0x43, 0x2b, 0x5f, 0xa4, 0x0a, 0x2f, 0x45, 0xe9, 0x22, 0xfd, 0xc1, 0x4d, 0x4b,
	0xb5, 0xe5, 0xfb, 0x08, 0x9a, 0xcb, 0x66, 0xa0, 0xa4, 0x3e, 0xd6, 0x52, 0xb6, 0x2b, 0x59, 0xa1,
	0x4f, 0xa0, 0xae, 0xc0, 0xce, 0x12, 0x39, 0x65, 0x09, 0xf5, 0xbb, 0x3a, 0xa2, 0xc0, 0xc4, 0x85,
	0xa5, 0xa0, 0x1f, 0xc0, 0xa6, 0xc8, 0x68, 0x28, 0xfc, 0x8f, 0x74, 0x04, 0xd7, 0x87, 0x85, 0x9a,
	0x2f, 0xd8, 0x48, 0xa0, 0x3d, 0xd8, 0xfa, 0x6e, 0x41, 0x17, 0x34, 0xf2, 0x1f, 0x98, 0xba, 0x31,
	0xb7, 0xb1, 0xe3, 0x56, 0xbd, 0x8d, 0xb1, 0xe3, 0x6e, 0x78, 0x8e, 0x29, 0xc9, 0xb2, 0x59, 0x36,
	0xbc, 0xe6, 0xd8, 0x71, 0xdb, 0x9e, 0x37, 0x76, 0x5c, 0xcf, 0xeb, 0x8c, 0x1d, 0x77, 0xc7, 0xdb,
	0x1d, 0x3b, 0xee, 0xae, 0xb7, 0x37, 0x76, 0xdc, 0x3d, 0x6f, 0x7f, 0xec, 0xb8, 0x07, 0xde, 0x47,
	0x63, 0xc7, 0xdd, 0xf7, 0xfc, 0xb1, 0xe3, 0xfa, 0xde, 0x03, 0xdc, 0x8d, 0x58, 0x4e, 0x43, 0xc9,
	0x73, 0x46, 0x45, 0x70, 0x43, 0x64, 0x38, 0xa3, 0x11, 0x6e, 0x66, 0x44, 0xce, 0x96, 0xd7, 0x9d,
	0xbb, 0xc8, 0xcb, 0x29, 0x11, 0x3c, 0xc5, 0x6b, 0x78, 0x34, 0x4d, 0xba, 0x56, 0x60, 0x40, 0x60,
	0x2f, 0x0a, 0xef, 0xa6, 0x07, 0xa3, 0x5b, 0x32, 0x5f, 0x4b, 0x19, 0xee, 0x88, 0x19, 0xbf, 0x29,
	0x20, 0xad, 0x83, 0x88, 0x1b, 0x21, 0x9f, 0x5f, 0xb2, 0x94, 0xea, 0x36, 0x83, 0x6b, 0x66, 0x9a,
	0xa8, 0x63, 0xa7, 0x3c, 0x06, 0xb6, 0x8d, 0xe1, 0x2d, 0x92, 0xd0, 0x5c, 0x0a, 0xbc, 0x35, 0x25,
	0x21, 0x95, 0xa2, 0xc7, 0xa0, 0xa6, 0x62, 0x6d, 0x6a, 0xc6, 0x87, 0xed, 0x6b, 0x9a, 0x0b, 0xc6,
	0xd3, 0x62, 0x12, 0xd8, 0x2b, 0x3a, 0x84, 0x5a, 0xc8, 0xe7, 0x73, 0x26, 0x27, 0xcf, 0x4f, 0x6d,
	0x9b, 0x59, 0x12, 0x54, 0x7b, 0x29, 0x87, 0x73, 0x0d, 0xeb, 0xb3, 0xea, 0x52, 0x11, 0xbd, 0xd6,
	0x1d, 0xc5, 0xc5, 0xea, 0xd8, 0xfb, 0x19, 0xb4, 0xbf, 0x35, 0xe6, 0x26, 0x54, 0x4a, 0x3d, 0x76,
	0x1f, 0x41, 0x33, 0x9c, 0xd1, 0xf0, 0xca, 0x8e, 0x0d, 0xa1, 0xdd, 0xba, 0xb8, 0xa1, 0x89, 0x66,
	0x5c, 0x88, 0xde, 0x3f, 0xb7, 0xc1, 0xf9, 0x96, 0xd1, 0x1b, 0x65, 0x32, 0xe1, 0x71, 0xd1, 0xf8,
	0x12, 0x1e, 0xa3, 0x3e, 0xd4, 0x8a, 0xe8, 0x08, 0xbf, 0xaa, 0x11, 0xd2, 0x29, 0x11, 0x52, 0x80,
	0x16, 0x2f, 0x65, 0xd0, 0x53, 0x78, 0x30, 0x1c, 0xbd, 0xc1, 0xa3, 0xc1, 0xe9, 0xc5, 0x68, 0xa8,
	0x03, 0x53, 0x6e, 0x34, 0xc2, 0xee, 0x16, 0xfb, 0x4b, 0x81, 0x73, 0x1e, 0x97, 0x7d, 0x41, 0xa0,
	0x21, 0x34, 0xa7, 0x94, 0xc8, 0x45, 0x4e, 0x83, 0x69, 0x42, 0x62, 0x35, 0xb1, 0x94, 0xc3, 0x4f,
	0x4a, 0x87, 0xea, 0x23, 0x8f, 0xbf, 0x31, 0x22, 0xdf, 0x28, 0x89, 0x51, 0x2a, 0xf3, 0x5b, 0xdc,
	0x98, 0xae, 0x90, 0xd0, 0x09, 0xec, 0xa6, 0x94, 0x46, 0x22, 0x20, 0x29, 0x49, 0x6e, 0x25, 0x0b,
	0x45, 0x90, 0x2e, 0x22, 0x3b, 0xd8, 0x5c, 0xdc, 0xd5, 0xcc, 0xd3, 0x82, 0xf7, 0x4a, 0xb1, 0xd0,
	0xaf, 0x00, 0xe5, 0x8b, 0x54, 0x6d, 0x2a, 0xba, 0x54, 0x6c, 0x2f, 0xdc, 0xd2, 0xc5, 0x8b, 0x96,
	0x15, 0x51, 0xe4, 0x11, 0x7b, 0x56, 0x7a, 0x99, 0xd9, 0x09, 0x1c, 0xae, 0xbe, 0x5b, 0xc5, 0x55,
	0xae, 0xda, 0xda, 0x7e, 0xaf, 0xad, 0x95, 0x78, 0x9d, 0x6b, 0xb5, 0xa5, 0xd1, 0x2f, 0x61, 0x4f,
	0x2c, 0xe2, 0x98, 0x0a, 0x49, 0x23, 0x63, 0xac, 0x40, 0x8f, 0xa7, 0x53, 0xb4, 0x53, 0x72, 0x95,
	0x8e, 0xcd, 0x3d, 0x1a, 0x80, 0x67, 0xc5, 0x02, 0x61, 0x71, 0xe0, 0x37, 0xd6, 0xfa, 0xd9, 0x1a,
	0x4e, 0x70, 0xfb, 0x7a, 0x0d, 0x38, 0xc7, 0xd0, 0xd5, 0x0e, 0xc3, 0x84, 0x2f, 0xa2, 0x60, 0x21,
	0x68, 0xae, 0xe7, 0x9b, 0xd9, 0x8c, 0x3a, 0x8a, 0x35, 0x50, 0x9c, 0xb7, 0x96, 0x81, 0xfa, 0xb0,
	0xb3, 0x22, 0x2f, 0x29, 0x99, 0x9b, 0x85, 0xa7, 0xbd, 0xa6, 0x70, 0x41, 0xc9, 0x5c, 0xaf, 0x3e,
	0x27, 0xb0, 0xbb, 0xa2, 0x20, 0xc2, 0x19, 0x9d, 0xd3, 0xe7, 0x5c, 0x48, 0xbb, 0x07, 0x74, 0x4b,
	0x8d, 0x49, 0xc9, 0x52, 0xeb, 0xd2, 0x9a, 0x93, 0xb3, 0xa1, 0x1e, 0x38, 0x35, 0xdc, 0xbe, 0xe3,
	0xe1, 0x6c, 0xa8, 0x1a, 0xdf, 0x94, 0x48, 0x92, 0x04, 0x66, 0x51, 0xad, 0x6b, 0x29, 0xd0, 0xa4,
	0x91, 0xde, 0x56, 0x7f, 0x08, 0xae, 0x82, 0x67, 0xc2, 0x84, 0xd4, 0x03, 0xa1, 0x7e, 0xe2, 0xad,
	0xb4, 0xe9, 0xf8, 0x9c, 0x09, 0x89, 0xb7, 0x13, 0x73, 0x40, 0x5f, 0x83, 0x76, 0xb0, 0xba, 0x76,
	0xb5, 0x3e, 0x38, 0xe8, 0x9a, 0x4a, 0x65, 0xb9, 0x8d, 0xa9, 0x49, 0x6e, 0xbb, 0x6e, 0x70, 0x45,
	0x6f, 0xf5, 0x6c, 0xa8, 0xe1, 0x7a, 0x41, 0x7b, 0x41, 0x6f, 0x0f, 0x7e, 0x09, 0x9d, 0x7b, 0xf0,
	0x56, 0x55, 0xa9, 0xc4, 0x6d, 0x55, 0x5e, 0xd1, 0x5b, 0x35, 0xc8, 0xae, 0x49, 0xb2, 0xa0, 0x76,
	0x7f, 0x31, 0x97, 0xa7, 0xd5, 0x27, 0x95, 0xb1, 0xe3, 0x22, 0xaf, 0x8b, 0xdb, 0x73, 0x2a, 0x73,
	0x05, 0x7c, 0x41, 0xf3, 0x6b, 0x96, 0xc6, 0xbd, 0x67, 0xd0, 0x7a, 0x69, 0x48, 0x13, 0x43, 0x51,
	0x1d, 0x45, 0xaf, 0x13, 0x76, 0x61, 0x51, 0x67, 0xf5, 0x81, 0x71, 0x4e, 0xa6, 0x24, 0x25, 0xc1,
	0x8c, 0xdb, 0xed, 0xa8, 0x86, 0xeb, 0x96, 0xa6, 0x32, 0xd0, 0xf3, 0xa0, 0xf5, 0x8c, 0x4a, 0x55,
	0x87, 0x98, 0x7e, 0xb7, 0x50, 0x4b, 0x93, 0x80, 0xce, 0x24, 0x25, 0x99, 0x98, 0x71, 0xf9, 0x9c,
	0xc5, 0xb3, 0x84, 0xc5, 0x33, 0x89, 0x3e, 0x87, 0xf6, 0x25, 0x8d, 0x99, 0xa9, 0xa8, 0x84, 0xc7,
	0x67, 0x43, 0xeb, 0xa8, 0x55, 0x92, 0xcf, 0x15, 0x55, 0xb9, 0xb4, 0x3d, 0xdb, 0x48, 0x59, 0x97,
	0x86, 0x66, 0x44, 0x10, 0x38, 0x92, 0xfe, 0x4e, 0x16, 0xbd, 0x4f, 0x9d, 0x7b, 0xff, 0xa8, 0x80,
	0x5b, 0x78, 0x45, 0x9f, 0x82, 0xa3, 0x92, 0xa6, 0x3d, 0xac, 0xae, 0x00, 0xfa, 0x2b, 0x35, 0x4b,
	0x01, 0x87, 0x89, 0x40, 0xb0, 0x88, 0x5e, 0x92, 0x5c, 0xc1, 0x47, 0xd0, 0xc8, 0x06, 0xaf, 0xcd,
	0xc4, 0xc4, 0xd0, 0x07, 0x9a, 0xac, 0xfc, 0xa9, 0x61, 0x53, 0xf8, 0x53, 0x67, 0x74, 0x06, 0x48,
	0x58, 0x77, 0xc1, 0xac, 0x78, 0x65, 0xb9, 0xcc, 0x15, 0x0e, 0xef, 0xc5, 0x01, 0x77, 0xc4, 0xbd,
	0xd0, 0x3c, 0x82, 0x66, 0x69, 0x4a, 0xad, 0x2e, 0x76, 0xdf, 0x6e, 0x14, 0x44, 0xb5, 0xaa, 0xf4,
	0x1e, 0xc3, 0xde, 0xdb, 0x2c, 0xe1, 0x24, 0x2a, 0x4c, 0x62, 0x2a, 0x32, 0x9e, 0x0a, 0x7a, 0x7f,
	0x37, 0xed, 0xfd, 0x01, 0xba, 0xa7, 0xe1, 0xd5, 0xaf, 0xe9, 0xa5, 0xe0, 0xe1, 0x15, 0x95, 0x36,
	0x2f, 0xca, 0x8f, 0xe4, 0x81, 0xee, 0xf3, 0x7a, 0xfc, 0x69, 0x95, 0x4d, 0xdc, 0x90, 0x7c, 0x50,
	0xd2, 0xde, 0x05, 0xeb, 0xea, 0xff, 0x08, 0xeb, 0xde, 0x1e, 0xec, 0xdc, 0xf5, 0x6f, 0xbe, 0xf4,
	0xf1, 0x9f, 0x2a, 0xc5, 0x6f, 0x54, 0xf5, 0x83, 0x13, 0x7d, 0x04, 0xfb, 0x17, 0xa7, 0xf8, 0xd9,
	0xe8, 0x22, 0xb8, 0xf8, 0xcd, 0x9b, 0x51, 0xf0, 0xf6, 0xd5, 0xe4, 0xcd, 0x68, 0x70, 0xf6, 0xcd,
	0xd9, 0x68, 0xe8, 0xfd, 0x1f, 0xda, 0x85, 0xce, 0x2a, 0xf3, 0xec, 0xe5, 0xe9, 0xb3, 0x91, 0x57,
	0x41, 0x5d, 0x68, 0xaf, 0x92, 0x5f, 0x3c, 0x99, 0x78, 0x55, 0xf4, 0xff, 0x70, 0xb0, 0x4a, 0x1c,
	0xbe, 0x1e, 0xbc, 0x18, 0xe1, 0x60, 0xf0, 0xfa, 0xe5, 0x9b, 0xd7, 0x93, 0x91, 0xb7, 0xb1, 0x6e,
	0xeb, 0xfc, 0xf5, 0xe0, 0xf4, 0xdc, 0x73, 0x4e, 0xfe, 0x56, 0x81, 0xba, 0x42, 0x84, 0x2e, 0x80,
	0x50, 0x6d, 0xe7, 0xdb, 0x16, 0xc9, 0x68, 0xbf, 0xcc, 0xe0, 0x5d, 0x6c, 0x1f, 0xdc, 0xc5, 0x52,
	0xaf, 0xf3, 0xc7, 0xbf, 0xff, 0xeb, 0xcf, 0xd5, 0x3a, 0xaa, 0xe9, 0x1f, 0xf3, 0x1a, 0x58, 0x97,
	0xd0, 0xba, 0x9b, 0x28, 0xd4, 0xb9, 0x07, 0x87, 0x83, 0xe5, 0x00, 0x7b, 0x77, 0x52, 0x7b, 0x87,
	0xda, 0xf0, 0x5e, 0xaf, 0xa3, 0x0d, 0x17, 0x48, 0xe8, 0xa7, 0xf4, 0xe6, 0x69, 0xe5, 0xf1, 0xc9,
	0xef, 0xc1, 0x2b, 0xa3, 0x5b, 0x7c, 0xfd, 0x14, 0x1a, 0xab, 0x41, 0x47, 0x87, 0xa5, 0x8b, 0x77,
	0x60, 0xe1, 0xe0, 0xe3, 0xf7, 0x70, 0xad, 0xfb, 0x07, 0xda, 0x7d, 0xb7, 0xd7, 0xea, 0xdf, 0x14,
	0xbc, 0x3e, 0x09, 0xaf, 0x9e, 0x56, 0x1e, 0x7f, 0xfd, 0xd9, 0x6f, 0xbf, 0x17, 0x33, 0x39, 0x5b,
	0x5c, 0x1e, 0x87, 0x7c, 0xde, 0x57, 0x89, 0xff, 0x51, 0x44, 0xaf, 0xf5, 0xa1, 0xbf, 0xf2, 0x9f,
	0x89, 0xcb, 0x2d, 0x8d, 0x93, 0x9f, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x69, 0x7c, 0xa9,
	0x0f, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ViewServiceClient is the client API for ViewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ViewServiceClient interface {
	GetView(ctx context.Context, in *GetViewRequest, opts ...grpc.CallOption) (*View, error)
	UploadSnapshot(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*UploadSnapshotResponse, error)
}

type viewServiceClient struct {
	cc *grpc.ClientConn
}

func NewViewServiceClient(cc *grpc.ClientConn) ViewServiceClient {
	return &viewServiceClient{cc}
}

func (c *viewServiceClient) GetView(ctx context.Context, in *GetViewRequest, opts ...grpc.CallOption) (*View, error) {
	out := new(View)
	err := c.cc.Invoke(ctx, "/webview.ViewService/GetView", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewServiceClient) UploadSnapshot(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*UploadSnapshotResponse, error) {
	out := new(UploadSnapshotResponse)
	err := c.cc.Invoke(ctx, "/webview.ViewService/UploadSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ViewServiceServer is the server API for ViewService service.
type ViewServiceServer interface {
	GetView(context.Context, *GetViewRequest) (*View, error)
	UploadSnapshot(context.Context, *Snapshot) (*UploadSnapshotResponse, error)
}

// UnimplementedViewServiceServer can be embedded to have forward compatible implementations.
type UnimplementedViewServiceServer struct {
}

func (*UnimplementedViewServiceServer) GetView(ctx context.Context, req *GetViewRequest) (*View, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetView not implemented")
}
func (*UnimplementedViewServiceServer) UploadSnapshot(ctx context.Context, req *Snapshot) (*UploadSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadSnapshot not implemented")
}

func RegisterViewServiceServer(s *grpc.Server, srv ViewServiceServer) {
	s.RegisterService(&_ViewService_serviceDesc, srv)
}

func _ViewService_GetView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServiceServer).GetView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webview.ViewService/GetView",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServiceServer).GetView(ctx, req.(*GetViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ViewService_UploadSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Snapshot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServiceServer).UploadSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webview.ViewService/UploadSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServiceServer).UploadSnapshot(ctx, req.(*Snapshot))
	}
	return interceptor(ctx, in, info, handler)
}

var _ViewService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webview.ViewService",
	HandlerType: (*ViewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetView",
			Handler:    _ViewService_GetView_Handler,
		},
		{
			MethodName: "UploadSnapshot",
			Handler:    _ViewService_UploadSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/webview/view.proto",
}

// WebsocketServiceClient is the client API for WebsocketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebsocketServiceClient interface {
	AckWebsocket(ctx context.Context, in *AckWebsocketRequest, opts ...grpc.CallOption) (*AckWebsocketResponse, error)
}

type websocketServiceClient struct {
	cc *grpc.ClientConn
}

func NewWebsocketServiceClient(cc *grpc.ClientConn) WebsocketServiceClient {
	return &websocketServiceClient{cc}
}

func (c *websocketServiceClient) AckWebsocket(ctx context.Context, in *AckWebsocketRequest, opts ...grpc.CallOption) (*AckWebsocketResponse, error) {
	out := new(AckWebsocketResponse)
	err := c.cc.Invoke(ctx, "/webview.WebsocketService/AckWebsocket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebsocketServiceServer is the server API for WebsocketService service.
type WebsocketServiceServer interface {
	AckWebsocket(context.Context, *AckWebsocketRequest) (*AckWebsocketResponse, error)
}

// UnimplementedWebsocketServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWebsocketServiceServer struct {
}

func (*UnimplementedWebsocketServiceServer) AckWebsocket(ctx context.Context, req *AckWebsocketRequest) (*AckWebsocketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AckWebsocket not implemented")
}

func RegisterWebsocketServiceServer(s *grpc.Server, srv WebsocketServiceServer) {
	s.RegisterService(&_WebsocketService_serviceDesc, srv)
}

func _WebsocketService_AckWebsocket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckWebsocketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsocketServiceServer).AckWebsocket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webview.WebsocketService/AckWebsocket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsocketServiceServer).AckWebsocket(ctx, req.(*AckWebsocketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WebsocketService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webview.WebsocketService",
	HandlerType: (*WebsocketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AckWebsocket",
			Handler:    _WebsocketService_AckWebsocket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/webview/view.proto",
}
