apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: uselessmachines.tilt.dev
spec:
  group: tilt.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                nonImage:
                  type: string
  scope: Namespaced
  names:
    plural: uselessmachines
    singular: uselessmachine
    kind: UselessMachine
    shortNames:
    - um