apiVersion: v1
kind: ServiceAccount
metadata:
  name: tilt-integration-user
  namespace: tilt-integration
---
apiVersion: v1
kind: Secret
metadata:
  name: tilt-integration-user
  namespace: tilt-integration
  annotations:
    kubernetes.io/service-account.name: "tilt-integration-user"
type: kubernetes.io/service-account-token
