# -*- mode: Python -*-

docker_prune_settings(disable=True)

# HACK: load namespaces on `tilt up` but not on `tilt down`
load_namespace = not os.environ.get('SKIP_NAMESPACE', '')
if load_namespace:
  k8s_yaml('namespace.yaml')
