# -*- mode: Python -*-

custom_build(
  'gcr.io/windmill-test-containers/integration/oneup-custom',
  'docker build -t $EXPECTED_REF .',
  ["Dockerfile", "main.go"],
 )
k8s_resource('oneup-custom', 'oneup_custom.yaml', port_forwards=8100)

